Modify gaIdke-post-commit to smudge correctly after git pull
In GIT versions prior to 2.6.6 'git checkout HEAD' would execute
unconditionally and smudge the file. This no longer happens if
the file to be checked out is identical to the GIT archive file
and has a time stamp of the same second as the GIT archive file.
For this reason the .gaidke backup is moved back to make it
different to the committed file, which also removes it, because
the checked out file overwrites it with the committed file.

If called via 'post-checkout', there is no backup file $path.gaidke.
To smudge correctly for GIT >= 2.6.6, $path in working directory
must be removed.

.git_filters/gaIdke-activate:    change error message from Oops to Error:
.git_filters/gaIdke-post-commit: remove $path from WD if called via 'post-checkout'
.git_filters/gaIdke-pre-commit:  change error message from Oops to Error:
.git_filters/gaIdke-reset:       change error message from Oops to Error:

    Id: .git_filters/gaIdke-activate 1.5
    Id: .git_filters/gaIdke-post-commit 1.10
    Id: .git_filters/gaIdke-pre-commit 1.16
    Id: .git_filters/gaIdke-reset 1.2

diff --git a/.git_filters/gaIdke-activate b/.git_filters/gaIdke-activate
--- a/.git_filters/gaIdke-activate
+++ b/.git_filters/gaIdke-activate
@@ -1,7 +1,7 @@
 #!/bin/bash
 ########################################################################
 #
-# $Id: gaIdke-activate 1.4 $
+# $Id: gaIdke-activate 1.5 $
 # $IdBlockFurtherExpansion$
 #
 #  Copyright © 2016 John E Wulff <immediatec@gmail.com>
@@ -116,5 +116,5 @@ if [ -n "$git_base" ]; then
     echo "'Automatic GIT Id Keyword Expansion' gaIdke has been activated" >&2
     cd $mywd
 else
-    echo "Oops, you are not in a GIT project" >&2
+    echo "Error: gaIdke-activate: you are not in a GIT project" >&2
 fi
diff --git a/.git_filters/gaIdke-reset b/.git_filters/gaIdke-reset
--- a/.git_filters/gaIdke-reset
+++ b/.git_filters/gaIdke-reset
@@ -1,7 +1,7 @@
 #!/bin/sh
 ########################################################################
 #
-# $Id: gaIdke-reset 1.1 $
+# $Id: gaIdke-reset 1.2 $
 # $IdBlockFurtherExpansion$
 #
 #  Copyright © 2016 John E Wulff <immediatec@gmail.com>
@@ -80,5 +80,5 @@ if [ -n "$git_base" ]; then
     fi
     cd $mywd
 else
-    echo "Oops, you are not in a GIT project" >&2
+    echo "Error: gaIdke-reset: you are not in a GIT project" >&2
 fi
