RCS	icc.v	1.65	2001/05/06 20:10:28
handle extern imm declaration and imm declaration to allow linking
assume Time::HiRes is installed

CVS-ID: src/README 1.6
CVS-ID: src/comp.h 1.20
CVS-ID: src/comp.y 1.52
CVS-ID: src/genr.c 1.41
CVS-ID: src/iCbox 1.34
CVS-ID: src/iClive 1.16
CVS-ID: src/iCmake 1.18
CVS-ID: src/iCserver 1.24
CVS-ID: src/icc.h 1.32
CVS-ID: src/icc.v 1.65
CVS-ID: src/init.c 1.13
CVS-ID: src/link.c 1.15
CVS-ID: src/mklst 1.6
CVS-ID: src/outp.c 1.42
CVS-ID: src/symb.c 1.8

diff --git a/src/iCmake b/src/iCmake
--- a/src/iCmake
+++ b/src/iCmake
@@ -31,8 +31,9 @@ usage ()
     echo '	-v<N>	use ict<N> eg ict1 ict2 ... with libict1.a libict2.a ...' >&2
     echo '	-6	produce logic generation listing file.lst6' >&2
     echo '		default listing is file.lst' >&2
+    echo '	-x	auxiliary files _list1.h _list2.h _list_.c not deleted' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: iCmake,v 1.17 2001/04/04 10:30:37 jw Exp $' >&2
+    echo '	$Id: iCmake,v 1.18 2001/04/17 07:43:50 jw Exp $' >&2
 }
 
 link=0
@@ -42,6 +43,7 @@ v=""
 b=""
 lib="-lict"
 d="-d74 -A"
+x=""
 l=""
 
 while [ $# -gt 0 ]; do
@@ -66,6 +68,7 @@ while [ $# -gt 0 ]; do
 		b="./"
 		break;;
 	    6*)	d="-d76 -A";l="6";;
+	    x*)	x="1";;
 	    h*)	usage; exit 255;;
 	    *) aflag="-$option"; break;;
 	    esac
@@ -144,5 +147,7 @@ if [ "$link" = 1 ]; then
     fi
 fi
 
-# clean up temporary files generated by ict compiler
-rm -f _list1.h _list2.h _list_.c
+# clean up temporary files generated by ict compiler unless -x option
+if [ "$x" != 1 ]; then
+    rm -f _list1.h _list2.h _list_.c
+fi
