RCS	icc.v	1.101	2004/02/02 11:15:46
Makefile.in makeAll: add option -o<obj_extension> to makeAll to take care of Windows
cexe.h main.c outp.c: leave out union in Symbol if YYDEBUG for easier ddd debugging
comp.y genr.c icc.h icg.h init.c: extensive additions - imm function definition and call
gram.y lmain.c: include stdlib.h
iClive: add make item - Save &Make unconditionally; add iC icon
iCmake: add option -d<dir> use icc and (pplstfix libict.a unless -v first) in directory <dir>
icc.c ict.c link.c load.c main.c rsff.c symb.c tcpc.c: clean up to pass -Wall
makeAll: add option -d to make with DEQ
manifest: add dasgnq.ic to test dasgn with output Q... which never worked before
pplstfix: Re-format listing using longest identifier - other corrections

CVS-ID: src/Makefile.in 1.40
CVS-ID: src/cexe.h 1.20
CVS-ID: src/comp.h 1.42
CVS-ID: src/comp.y 1.83
CVS-ID: src/genr.c 1.56
CVS-ID: src/gram.y 1.17
CVS-ID: src/iClive 1.31
CVS-ID: src/iCmake 1.27
CVS-ID: src/icc.c 1.26
CVS-ID: src/icc.h 1.51
CVS-ID: src/icc.v 1.101
CVS-ID: src/icg.h 1.4
CVS-ID: src/ict.c 1.38
CVS-ID: src/init.c 1.23
CVS-ID: src/link.c 1.22
CVS-ID: src/lmain.c 1.9
CVS-ID: src/load.c 1.41
CVS-ID: src/main.c 1.43
CVS-ID: src/makeAll 1.16
CVS-ID: src/manifest 1.9
CVS-ID: src/outp.c 1.72
CVS-ID: src/pplstfix 1.11
CVS-ID: src/rsff.c 1.36
CVS-ID: src/symb.c 1.15
CVS-ID: src/tcpc.c 1.13

diff --git a/src/iCmake b/src/iCmake
--- a/src/iCmake
+++ b/src/iCmake
@@ -19,7 +19,7 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/}' [-[l|o<exe>|s|c|b|n]i6xqh] [-v[<N>]] file.ic ...' >&2
+    echo 'Usage:	'${0##*/}' [-[l|o<exe>|s|c|b|n]i6xqh] [-v[<N>]] [-d<dir>] file.ic ...' >&2
     echo '    (default)	link all iCfiles file.ic ... into independent executables' >&2
     echo '		output names are base names of the iCfiles (file ...)' >&2
     echo '	-l	link all iCfiles into one executable' >&2
@@ -36,10 +36,11 @@ usage ()
     echo '	-x	auxiliary files _list1.h _list2.h _list_.c not deleted' >&2
     echo '	-q	quiet operation - return status only' >&2
     echo '	-v	use icc, pplstfix and libict.a in local directory' >&2
-    echo '		(default use installed icc and -lict)' >&2
     echo '	-v<N>	use icc<N> eg icc1 icc2 ... with libict1.a libict2.a ...' >&2
+    echo '	-d<dir>	use icc and (pplstfix libict.a unless -v first) in directory <dir>' >&2
+    echo '		(default use installed icc and -lict)' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: iCmake,v 1.26 2004/01/02 16:50:45 jw Exp $' >&2
+    echo '	$Id: iCmake,v 1.27 2004/01/09 11:40:36 jw Exp $' >&2
 }
 
 link=0
@@ -49,7 +50,7 @@ a=""
 v=""
 b=""
 lib="-lict"
-dir="/usr/local/lib"
+ldir="-L/usr/local/lib"
 d="-d474 -A"
 x=""
 l=""
@@ -90,14 +91,29 @@ while [ $# -gt 0 ]; do
 	    I*)	i=540;;
 	    q*)	q=1;;
 	    v*)	option=${option#?}
-		if [ -n "$option" ]; then
-		    lib=./libict$option.a
-		    v="$option -P./"
-		else
-		    lib=./libict.a
-		    v=" -P./"
+		if [ -z "$b" ]; then
+		    b="./"
 		fi
-		b="./"
+		lib=${b}libict$option.a
+		ldir=""
+		v="$option -P${b}"
+		break;;
+	    d*)	option=${option#?}
+		if [ -z "$option" ]; then
+		    shift
+		    option=$1
+		fi
+		option=${option%/}
+		if [ ! -d "$option/" ]; then
+		    echo "Error: -d '$option/' is not a directory" >&2
+		    exit 254;
+		fi
+		b="$option/"
+		if [ -z "$v" ]; then
+		    lib=${b}libict.a
+		    ldir=""
+		    v=" -P${b}"
+		fi
 		break;;
 	    6*)	d="-d476 -A";l="6";;
 	    x*)	d="-d4474 -A";x="1";;
@@ -130,7 +146,7 @@ for f in $*; do
 	    rm -f $base.c $base
 	    if nice ${b}icc$v $d -o $base.c -l $base.lst$l $file; then
 		echo >> _list2.h	# terminate last line of #define \
-		if nice gcc -g -I. -L$dir -o $base $base.c _list_.c $lib; then
+		if nice gcc -g -I. $ldir -o $base $base.c _list_.c $lib; then
 		    if [ -n "$i" ] && ! ./$base -d$i > $base.ini; then
 			if [ "$q" = 0 ]; then
 			    echo "run time error in initial execution of '$base'" >&2
@@ -229,7 +245,7 @@ if [ "$link" = 1 ]; then
 	    echo "link $first from$list"
 	fi
 	echo >> _list2.h	# terminate last line of #define \
-	if nice gcc -g -I. -L$dir -o $first $list _list_.c $lib; then
+	if nice gcc -g -I. $ldir -o $first $list _list_.c $lib; then
 	    if [ -n "$i" ] && ! ./$first -d$i > $first.ini; then
 		if [ "$q" = 0 ]; then
 		    echo "run time error in initial execution of '$first'" >&2
diff --git a/src/makeAll b/src/makeAll
--- a/src/makeAll
+++ b/src/makeAll
@@ -21,8 +21,8 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/}' [-qgctlmCTLMszh]' >&2
-    echo '	call make for icc, ict and libict.a with the correct options' >&2
+    echo 'Usage:	'${0##*/}' [-qgctlmdCTLMszh] [-o<OBJ>]' >&2
+    echo '	call make for icc, ict, libict.a and lmain with the correct options' >&2
     echo '	-q	output only headings and error messages' >&2
     echo '	-g	compile for debugging and no optimisation (default -O2)' >&2
     echo '	-c	make icc with YYDEBUG' >&2
@@ -30,6 +30,7 @@ usage ()
     echo '	-t	make ict with YYDEBUG -t trace output possible' >&2
     echo '	-l	make libict.a with YYDEBUG -t trace output possible' >&2
     echo '	-m	make lmain with YYDEBUG' >&2
+    echo '	-d	make all targets with DEQ option' >&2
     echo '	see usage of icc, icr, ict and applications for other options' >&2
     echo '	-C	make icc only; generate an empty cexe.c' >&2
     echo '	-R	make icr only without modifying cexe.c' >&2
@@ -42,59 +43,60 @@ usage ()
     echo '		no 32 bit arithmetic and rejects QL.. and IL.. I/O unless' >&2
     echo '	-z	make with -DLONG16        (make clean required first)' >&2
     echo '		produces code for long int arithmetic on a 16 bit system' >&2
+    echo '	-o<OBJ>	define object extension (o is default; obj for Windows)' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: makeAll,v 1.15 2004/01/03 08:32:39 jw Exp $' >&2
+    echo '	$Id: makeAll,v 1.16 2004/02/02 10:18:27 jw Exp $' >&2
 }
 
 makeIcr ()
 {
-    mv comp.o genr.o gram.o lexc.o link.o main.o outp.o rsff.o scan.o Make_tmp 2> /dev/null
+    mv comp.$O genr.$O gram.$O init.$O lexc.$O link.$O main.$O outp.$O rsff.$O scan.$O symb.$O Make_tmp 2> /dev/null
     if [ -d IcrObjs ]; then
 	mv IcrObjs/* .
     else
 	mkdir IcrObjs
     fi
-    make OPT="-DRUN$r$s$z" CFLAGS="$cflags" icr
-    mv comp.o genr.o gram.o lexc.o link.o main.o outp.o rsff.o scan.o IcrObjs
+    make OPT="-DRUN$r$d$s$z" CFLAGS="$cflags" icr
+    mv comp.$O genr.$O gram.$O init.$O lexc.$O link.$O main.$O outp.$O rsff.$O scan.$O symb.$O IcrObjs
     mv Make_tmp/* . 2> /dev/null
 }
 
 makeIct ()
 {
-    mv comp.o genr.o gram.o ict.o lexc.o link.o main.o outp.o rsff.o scan.o tcpc.o Make_tmp 2> /dev/null
+    mv comp.$O genr.$O gram.$O ict.$O init.$O lexc.$O link.$O main.$O outp.$O rsff.$O scan.$O symb.$O tcpc.$O Make_tmp 2> /dev/null
     if [ -d IctObjs ]; then
 	mv IctObjs/* .
     else
 	mkdir IctObjs
     fi
-    make OPT="-DTCP$t$s$z" CFLAGS="$cflags" ict
-    mv comp.o genr.o gram.o ict.o lexc.o link.o main.o outp.o rsff.o scan.o tcpc.o IctObjs
+    make OPT="-DTCP$t$d$s$z" CFLAGS="$cflags" ict
+    mv comp.$O genr.$O gram.$O ict.$O init.$O lexc.$O link.$O main.$O outp.$O rsff.$O scan.$O symb.$O tcpc.$O IctObjs
     mv Make_tmp/* . 2> /dev/null
 }
 
 makeLib ()
 {
-    mv ict.o link.o rsff.o scan.o tcpc.o  Make_tmp 2> /dev/null
+    mv ict.$O link.$O rsff.$O scan.$O tcpc.$O  Make_tmp 2> /dev/null
     if [ -d LibObjs ]; then
 	mv LibObjs/* .
     else
 	mkdir LibObjs
     fi
-    make OPT="-DLOAD -DTCP$l$s$z" CFLAGS="$cflags" libict.a
-    mv ict.o link.o rsff.o scan.o tcpc.o  LibObjs
+    make OPT="-DLOAD -DTCP$l$d$s$z" CFLAGS="$cflags" libict.a
+    mv ict.$O link.$O rsff.$O scan.$O tcpc.$O  LibObjs
     mv Make_tmp/* . 2> /dev/null
 }
 
 makeLmain ()
 {
-    mv gram.o lexc.o Make_tmp 2> /dev/null
+    mv gram.$O lexc.$O Make_tmp 2> /dev/null
     if [ -d LmainObjs ]; then
 	mv LmainObjs/* .
     else
 	mkdir LmainObjs
     fi
-    make OPT="-DLMAIN$m$s$z" CFLAGS="$cflags" lmain
-    mv gram.o lexc.o LmainObjs
+    make OPT="-DLMAIN$m$d$s$z" CFLAGS="$cflags" lmain
+    mv gram.$O lexc.$O LmainObjs
     mv Make_tmp/* . 2> /dev/null
 }
 
@@ -104,6 +106,7 @@ r=""
 t=""
 l=""
 m=""
+d=""
 s=""
 z=""
 C=0
@@ -113,6 +116,7 @@ L=0
 M=0
 ALL=1
 cflags="-O2"			# optimisation, no debugging info
+O="o"
 
 while [ $# -gt 0 ]; do
     case $1 in
@@ -127,6 +131,7 @@ while [ $# -gt 0 ]; do
 	    t*)	t=" -DYYDEBUG";;
 	    l*)	l=" -DYYDEBUG";;
 	    m*)	m=" -DYYDEBUG";;
+	    d*)	d=" -DDEQ";;
 	    s*)	s=" -DINT_MAX=32767";;
 	    z*)	z=" -DLONG16";;
 	    C*)	C=1; ALL=0;;
@@ -134,6 +139,13 @@ while [ $# -gt 0 ]; do
 	    T*)	T=1; ALL=0;;
 	    L*)	L=1; ALL=0;;
 	    M*)	M=1; ALL=0;;
+	    o*)	option=${option#?}
+		if [ -z "$option" ]; then
+		    shift
+		    option=$1
+		fi
+		O="$option"
+		break;;
 	    h*)	usage; exit 255;;
 	    *)	x=${option#?}; option=${option%$x}
 	    	echo "$name: unexpected option $option in $1" >&2
@@ -154,29 +166,36 @@ fi
 test -d Make_tmp || mkdir Make_tmp;
 
 if [ $ALL = 1 ] || [ $C = 1 ]; then
-    echo "make OPT=\"$c$s$z\" CFLAGS=\"$cflags\" icc"
-    make OPT="$c$s$z" CFLAGS="$cflags" icc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
-    if [ -z "$q" ]; then echo './icc -c < /dev/null		# make empty cexe.c'; fi
+    echo "make OPT=\"$c$d$s$z\" CFLAGS=\"$cflags\" icc"
+    make OPT="$c$d$s$z" CFLAGS="$cflags" icc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+    rm -f /tmp/cexe.c
+    test -f cexe.c && mv cexe.c /tmp			# current cexe.c for comparison
     ./icc -c < /dev/null
+    if cmp -s cexe.c /tmp/cexe.c; then
+	mv /tmp/cexe.c .				# restore version with old date
+    else
+	if [ -z "$q" ]; then echo './icc -c < /dev/null	# make new empty cexe.c'; fi
+	rm -f /tmp/cexe.c				# clean up in case another user wants to use it
+    fi
 fi
 
 if [ $ALL = 1 ] || [ $R = 1 ]; then
-    echo "make OPT=\"-DRUN$r$s$z\" CFLAGS=\"$cflags\" icr"
+    echo "make OPT=\"-DRUN$r$d$s$z\" CFLAGS=\"$cflags\" icr"
     makeIcr  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $ALL = 1 ] || [ $T = 1 ]; then
-    echo "make OPT=\"-DTCP$t$s$z\" CFLAGS=\"$cflags\" ict"
+    echo "make OPT=\"-DTCP$t$d$s$z\" CFLAGS=\"$cflags\" ict"
     makeIct  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $ALL = 1 ] || [ $L = 1 ]; then
-    echo "make OPT=\"-DLOAD -DTCP$l$s$z\" CFLAGS=\"$cflags\" libict.a"
+    echo "make OPT=\"-DLOAD -DTCP$l$d$s$z\" CFLAGS=\"$cflags\" libict.a"
     makeLib  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $ALL = 1 ] || [ $M = 1 ]; then
-    echo "make OPT=\"-DLMAIN$m$s$z\" CFLAGS=\"$cflags\" lmain"
+    echo "make OPT=\"-DLMAIN$m$d$s$z\" CFLAGS=\"$cflags\" lmain"
     makeLmain  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
