Corrections required by Linux Mint
Makefile.in  19 Make libdir, as 'configure' sets it, available to all iC apps - in particular to
                iCmake - via the the ini file ~/.iC/iCmake.ini by writing that file in
                'perlinstall -t $(srcdir) $(libdir)' called when executing 'make install'.
                Remove ~/.iC/iCmake.ini in 'perlinstall -r', which is called in 'make uninstall'.
             20 Re-arrange INSTALL calls to make things in the correct sequence.
                Fix testing of the existence of goserver and immag to install the correct programs.
iCmake       22 Simply testing for the existence of /usr/local/lib64 does not guarantee
                that the iC libraries libict.a and libict.so are actually installed
                in that library or in /usr/local/lib if it does not exist.
                A better way is to write the configured LIB path to the file ${HOME}/.iC/iCmake.ini
                from 'perlinstall -t', which is called early during the execution of 'make install'.
                iCmake then does a 'read LIB < ${HOME}/.iC/iCmake.ini' to get the path in which the
                iC libraries were actually installed - either /usr/local/lib64 or /usr/local/lib.
             23 LIB in ~/.iC/iCmake.ini does not have a trailing /.  Use $LIB without a trailing /.
perlinstall   2 For the -t option write the correct library path to ~/.iC/iCmake.ini.
                For the -r option rm -f ~/.iC/iCmake.ini.

    Id: src/Makefile.in 1.82
    Id: src/iCmake 1.56
    Id: src/perlinstall 1.12 <- perlinstall,v

diff --git a/src/iCmake b/src/iCmake
--- a/src/iCmake
+++ b/src/iCmake
@@ -17,27 +17,21 @@
 #
 ########################################################################
 
+name=${0##*/}
 if echo $PATH | grep -q intel_cc; then
     CC=icc
 else
     CC=gcc
 fi
 
-case `uname -m` in
-    *x86_64* | *ppc64* | *s390x* )
-	if [ -d "/usr/local/lib64/" ]; then
-	    LIB="/usr/local/lib64/"
-	else
-	    LIB="/usr/local/lib/"
-	fi
-	;;
-    *armv* )
-	LIB="/usr/local/lib/"
-	;;
-    * )
-	LIB="/usr/local/lib/"
-	;;
-esac
+if [ -f "${HOME}/.iC/iCmake.ini" ]; then
+    read LIB < ${HOME}/.iC/iCmake.ini
+    if [ ! -d $LIB -o ! -f "$LIB/libict.a" ]; then
+	echo "$name: iC system is configured with incorrect LIB '$LIB'" >&2; exit 125
+    fi
+else
+    echo "$name: iC system is not configured and installed" >&2; exit 126
+fi
 
 ldir=" -I/usr/local/include -L$LIB"
 ICC=immcc
@@ -46,7 +40,7 @@ IAC=immac
 usage ()
 {
   echo 'Usage:' >&2
-  echo '  '${0##*/}' [-[l|o<exe>|i|t|c|b|n]sfgASpRaLjIJ6xqNzh][ -v[<N>]][ -w<dir>]' >&2
+  echo "  $name [-[l|o<exe>|i|t|c|b|n]sfgASpRaLjIJ6xqNzh][ -v[<N>]][ -w<dir>]" >&2
   echo '         [ -k<lim>][ -d<opt>][ -O<level>][ -Dmacro[=defn]...][ -Umacro...]' >&2
   echo '         { -L<lx>][ -Cmacro[=defn]...][ -Vmacro...][ -Pmacro[=defn]...]' >&2
   echo '         [ -W[no-]<warn>...] file ...' >&2
@@ -117,7 +111,7 @@ usage ()
   echo '		(default: nice)' >&2
   echo '	-z	echo compiler calls with all options for debugging' >&2
   echo '	-h	this help text' >&2
-  echo '	$Id: iCmake 1.55 $' >&2
+  echo '	$Id: iCmake 1.56 $' >&2
 }
 
 lwsock32=""
@@ -135,7 +129,7 @@ v=""
 b=""
 #lib="-lict -lrt$lwsock32"
 lib="-lict$lwsock32"
-libfile="${LIB}libict.so"
+libfile="$LIB/libict.so"
 L=""
 d=" -d474"
 D=""
@@ -189,11 +183,11 @@ while getopts ":lo:itcbnsL:fegASpRaFk:EjIJ6xqNv:w:d:O:D:U:C:V:P:W:yzh" opt; do
 	    first=$OPTARG
 	    base=${first%.*}
 	    if [ "$first" = "$base.ic" -o "$first" = "$base.ih" ]; then
-		echo "parameter error - target -o '$first' is probably an iC source" >&2
+		echo "$name: parameter error - target -o '$first' is probably an iC source" >&2
 		exit 1
 	    fi
 	else
-	    echo "parameter error - no target name for -o option" >&2
+	    echo "$name: parameter error - no target name for -o option" >&2
 	    exit 2
 	fi
 	;;
@@ -202,11 +196,11 @@ while getopts ":lo:itcbnsL:fegASpRaFk:EjIJ6xqNv:w:d:O:D:U:C:V:P:W:yzh" opt; do
     c )	link=3; d="$A$S$N$R$k";;
     b ) link=4;;
     n ) link=5; d="$A$S$N$R$k";;
-    s ) lib="${LIB}libict.a$lwsock32"; libfile="${LIB}libict.a";;
+    s ) lib="$LIB/libict.a$lwsock32"; libfile="$LIB/libict.a";;
     L ) L="$L -$OPTARG";;
     f )	force=1;;
     e ) ef=" -lefence";;
-    g ) d="$d -g"; CFL="$CFL -g -pg"; lib="${LIB}libict.a$lwsock32"; libfile="${LIB}libict.a";;
+    g ) d="$d -g"; CFL="$CFL -g -pg"; lib="$LIB/libict.a$lwsock32"; libfile="$LIB/libict.a";;
     A )	if [ -z "$A" ]; then A=" -A"; d="$d$A"; fi;;
     S )	if [ -z "$S" ]; then S=" -S"; d="$d$S"; fi;;
     N )	if [ -z "$N" ]; then N=" -N"; d="$d$N"; fi;;
@@ -236,7 +230,7 @@ while getopts ":lo:itcbnsL:fegASpRaFk:EjIJ6xqNv:w:d:O:D:U:C:V:P:W:yzh" opt; do
 	;;
     w ) OPTARG=${OPTARG%/}
 	if [ ! -d "$OPTARG/" ]; then
-	    echo "Error: -d '$OPTARG/' is not a directory" >&2
+	    echo "$name: -w '$OPTARG/' is not a directory" >&2
 	    exit 254;
 	fi
 	b="$OPTARG/"
@@ -257,7 +251,7 @@ while getopts ":lo:itcbnsL:fegASpRaFk:EjIJ6xqNv:w:d:O:D:U:C:V:P:W:yzh" opt; do
     y ) nice="";;
     z )	z=1;;
     h )	usage; exit 0;;
-    \?)	echo "$name: illegal option '-$OPTARG'"; usage; exit 127;;
+    \?)	echo "$name: illegal option '-$OPTARG'" >&2; usage; exit 127;;
     esac
 done
 shift $(($OPTIND - 1))
@@ -358,7 +352,7 @@ for arg in $*; do
 	.c )	lk=3; d="$A$S$N$R$k";;
 	.ic )	;;
 	.ica )	;;
-	* )	echo "*** bad file extension '$ext' in '$arg'" >&2; usage; exit 127;;
+	* )	echo "$name: *** bad file extension '$ext' in '$arg'" >&2; usage; exit 127;;
 	esac
     fi
 
diff --git a/src/perlinstall b/src/perlinstall
--- a/src/perlinstall
+++ b/src/perlinstall
@@ -24,21 +24,29 @@
 #
 #	Option -r restores original scripts from backups *.hires
 #
+#	Also write and remove the ini file ~/.iC/iCmake.ini - JW 2023.02.10
+#
 ########################################################################
 
+name=${0##*/}
 usage ()
 {
-    echo "Usage:	${0##*/}" >&2
+    echo "Usage:	$name" >&2
     echo '		return the correct @INC path to install perl-modules' >&2
     echo '		error return if no @INC path found' >&2
-    echo "Or:	${0##*/} [-trh] [<srcdir>]" >&2
-    echo '	-t	test and modify perlscripts if Time::HiRes not installed' >&2
-    echo '	-r	restore modified perlscripts to use Time::HiRes' >&2
-    echo '		default source directory <srcdir> is .' >&2
-    echo '	-h	this help text' >&2
-    echo '	$Id: perlinstall,v 1.11 2009/08/21 06:08:40 jw Exp $' >&2
+    echo "Or:	$name -t [<srcdir>] <libdir>" >&2
+    echo '		test and modify perlscripts if Time::HiRes not installed' >&2
+    echo '		write the correct library path to ~/.iC/iCmake.ini' >&2
+    echo "Or:	$name -r [<srcdir>]" >&2
+    echo '		restore modified perlscripts to use Time::HiRes' >&2
+    echo '		rm -f ~/.iC/iCmake.ini' >&2
+    echo "Or:	$name -h" >&2
+    echo '		this help text' >&2
+    echo '	default source directory <srcdir> is .' >&2
+    echo '	$Id: perlinstall 1.12 $' >&2
 }
 
+## echo "DEBUG: $name '$1' '$2' '$3'" >&2
 srcdir='.'
 t=''
 r=''
@@ -65,16 +73,6 @@ if [ -d "$1" ]; then
     shift
 fi
 
-for d in $(perl -e 'print "@INC\n"'); do
-    if [ "$d" != '.' ] && [ -d "$d" ]; then
-	perlPath=$d;	# should always find direcory
-	temp="${perlPath#*site_perl}"
-	if [ "$perlPath" != "$temp" ]; then
-	    break;	# stop on the first site_perl entry
-	fi
-    fi
-done
-
 if [ -n "$t" ]; then
     if ! ${srcdir}/iCserver -h 2> /dev/null; then
 	# iCserver returned false, TIME_HIRES is not installed - modify
@@ -86,6 +84,19 @@ if [ -n "$t" ]; then
 	    chmod 555 $script
 	done
     fi
+    # create the ~/.iC ini directory during 'make install'
+    if [ ! -d "${HOME}/.iC" ]; then
+	mkdir "${HOME}/.iC"
+    fi
+    # obtain the library path of the installed iC libraries from the last argument
+    if [ -d "$1" ]; then
+	libdir=$1
+    else
+	echo "$name: -t was not called correctly with 2nd argument '$1'" >&2
+	exit 2
+    fi
+    # write the ini file containing the library path of the installed iC libraries
+    echo $libdir > "${HOME}/.iC/iCmake.ini"
 elif [ -n "$r" ]; then
     # makes sure that repeated install and restore works
     for hires in ${srcdir}/*.hires; do
@@ -95,9 +106,25 @@ elif [ -n "$r" ]; then
 	    mv -f $hires $script
 	fi
     done
-elif [ -n "$perlPath" ]; then
-    echo $perlPath
+    # remove the ini file containing the library path of the installed iC libraries
+    rm -f "${HOME}/.iC/iCmake.ini"
 else
-    echo 'NO /usr/lib/perl5/site_perl/5*/i586-linux - installation failed' >&2
-    exit 1
+    # obtain perlPath from @INC
+    for d in $(perl -e 'print "@INC\n"'); do
+	if [ "$d" != '.' -a -d "$d" ]; then
+	    perlPath=$d;	# should always find direcory
+	    temp="${perlPath#*site_perl}"
+	    if [ "$perlPath" != "$temp" ]; then
+		break;	# stop on the first site_perl entry
+	    fi
+	fi
+    done
+    if [ -n "$perlPath" ]; then
+	## echo "DEBUG: $name: perlPath = '$perlPath'" >&2
+	# return perlPath to calling 'make install'
+	echo $perlPath
+    else
+	echo "$name: no /usr/lib/perl5/site_perl/5*/i586-linux - installation failed" >&2
+	exit 1
+    fi
 fi
