RCS	icc.v	1.94	2003/10/03 23:36:40
Changes for SuSE Linux 8.1

CVS-ID: src/AuxTools/AuxTools.v 1.94
CVS-ID: src/AuxTools/Readme_develop 1.4
CVS-ID: src/AuxTools/m 1.2
CVS-ID: src/Makefile.in 1.33
CVS-ID: src/Readme_develop 1.4
CVS-ID: src/comp.h 1.38
CVS-ID: src/comp.y 1.77
CVS-ID: src/configure 1.4
CVS-ID: src/genr.c 1.54
CVS-ID: src/gram.y 1.14
CVS-ID: src/iClive 1.26
CVS-ID: src/iCmake 1.24
CVS-ID: src/icc.v 1.94
CVS-ID: src/lexc.l 1.17
CVS-ID: src/lmain.c 1.8
CVS-ID: src/m 1.2
CVS-ID: src/main.c 1.38
CVS-ID: src/outp.c 1.64
CVS-ID: src/symb.c 1.13

diff --git a/src/iCmake b/src/iCmake
--- a/src/iCmake
+++ b/src/iCmake
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 ########################################################################
 #
@@ -13,6 +13,7 @@
 #	make an executable file from an iC file
 #
 #	Use cc rather than gcc, to make this script usable on every Unix
+#	Cygnus does not understand cc - use gcc
 #
 ########################################################################
 
@@ -37,7 +38,7 @@ usage ()
     echo '		(default use installed ict and -lict)' >&2
     echo '	-v<N>	use ict<N> eg ict1 ict2 ... with libict1.a libict2.a ...' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: iCmake,v 1.23 2002/10/20 00:12:19 jw Exp $' >&2
+    echo '	$Id: iCmake,v 1.24 2003/10/03 18:45:13 jw Exp $' >&2
 }
 
 link=0
@@ -48,6 +49,7 @@ v=""
 b=""
 lib="-lict"
 d="-d474 -A"
+#d="-d4474 -A"
 x=""
 l=""
 q=0
@@ -96,6 +98,7 @@ while [ $# -gt 0 ]; do
 		b="./"
 		break;;
 	    6*)	d="-d476 -A";l="6";;
+#	    6*)	d="-d4476 -A";l="6";;
 	    x*)	x="1";;
 	    h*)	usage; exit 255;;
 	    *) aflag="-$option"; break;;
@@ -126,7 +129,7 @@ for f in $*; do
 	    rm -f $base.c $base
 	    if nice ${b}ict$v $d -o $base.c -l $base.lst$l $file; then
 		echo >> _list2.h	# terminate last line of #define \
-		if nice cc -g -I. -o $base $base.c _list_.c $lib; then
+		if nice gcc -g -I. -o $base $base.c _list_.c $lib; then
 		    if [ "$i" = 1 ] && ! ./$base -d540 > $base.ini; then
 			if [ "$q" = 0 ]; then
 			    echo "run time error in initial execution of '$base'" >&2
@@ -135,7 +138,7 @@ for f in $*; do
 		    fi
 		else
 		    if [ "$q" = 0 ]; then
-			echo "cc compile errors in '$base.c' - no executable '$base' generated" >&2
+			echo "gcc compile errors in '$base.c' - no executable '$base' generated" >&2
 		    fi
 		    let status+=1
 		fi
@@ -225,7 +228,7 @@ if [ "$link" = 1 ]; then
 	    echo "link $first from$list"
 	fi
 	echo >> _list2.h	# terminate last line of #define \
-	if nice cc -g -I. -o $first $list _list_.c $lib; then
+	if nice gcc -g -I. -o $first $list _list_.c $lib; then
 	    if [ "$i" = 1 ] && ! ./$first -d540 > $first.ini; then
 		if [ "$q" = 0 ]; then
 		    echo "run time error in initial execution of '$first'" >&2
@@ -234,7 +237,7 @@ if [ "$link" = 1 ]; then
 	    fi
 	else
 	    if [ "$q" = 0 ]; then
-		echo "cc link errors in '$list' - no executable '$first' generated" >&2
+		echo "gcc link errors in '$list' - no executable '$first' generated" >&2
 	    fi
 	    let status+=1
 	fi
