RCS	icc.v	1.99	2004/01/03 10:49:40
make standalone icc without run-time, make icr with keyboard run-time
generate cexe.c from compiled strings in cexe.h (no need to read at run time)
fix debug & 02 output only when #ifdef YYDEBUG
use icc standalone compiler rather than ict

CVS-ID: src/Makefile.in 1.37
CVS-ID: src/cexe.h 1.19
CVS-ID: src/comp.h 1.40
CVS-ID: src/comp.y 1.81
CVS-ID: src/iCmake 1.26
CVS-ID: src/icc.c 1.24
CVS-ID: src/icc.h 1.49
CVS-ID: src/icc.v 1.99
CVS-ID: src/ict.c 1.36
CVS-ID: src/link.c 1.20
CVS-ID: src/load.c 1.39
CVS-ID: src/main.c 1.40
CVS-ID: src/makeAll 1.15
CVS-ID: src/outp.c 1.70
CVS-ID: src/rsff.c 1.35
CVS-ID: src/scan.c 1.26

diff --git a/src/iCmake b/src/iCmake
--- a/src/iCmake
+++ b/src/iCmake
@@ -28,18 +28,18 @@ usage ()
     echo '	-s	generate listings file.lst .. only (-o target.lst optional)' >&2
     echo '	-c	generate C outputs file.c ... only (-o target.c optional)' >&2
     echo '	-b	generate both listing and C output' >&2
-    echo '	-n	generate no output, report ict compile errors only' >&2
+    echo '	-n	generate no output, report icc compile errors only' >&2
     echo "		-s and -n generate 'cexe.c' for last file as a side effect" >&2
     echo '	-i	produce file.ini which records output of an initial run' >&2
     echo '	-I	produce file.ini with full INITIALIZATION info (debug only)' >&2
     echo '	-6	produce logic generation listing file.lst6' >&2
     echo '	-x	auxiliary files _list1.h _list2.h _list_.c not deleted' >&2
     echo '	-q	quiet operation - return status only' >&2
-    echo '	-v	use ict, pplstfix and libict.a in local directory' >&2
-    echo '		(default use installed ict and -lict)' >&2
-    echo '	-v<N>	use ict<N> eg ict1 ict2 ... with libict1.a libict2.a ...' >&2
+    echo '	-v	use icc, pplstfix and libict.a in local directory' >&2
+    echo '		(default use installed icc and -lict)' >&2
+    echo '	-v<N>	use icc<N> eg icc1 icc2 ... with libict1.a libict2.a ...' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: iCmake,v 1.25 2003/12/05 19:26:14 jw Exp $' >&2
+    echo '	$Id: iCmake,v 1.26 2004/01/02 16:50:45 jw Exp $' >&2
 }
 
 link=0
@@ -128,7 +128,7 @@ for f in $*; do
 	case $link in
 	0)
 	    rm -f $base.c $base
-	    if nice ${b}ict$v $d -o $base.c -l $base.lst$l $file; then
+	    if nice ${b}icc$v $d -o $base.c -l $base.lst$l $file; then
 		echo >> _list2.h	# terminate last line of #define \
 		if nice gcc -g -I. -L$dir -o $base $base.c _list_.c $lib; then
 		    if [ -n "$i" ] && ! ./$base -d$i > $base.ini; then
@@ -145,13 +145,13 @@ for f in $*; do
 		fi
 	    else
 		if [ "$q" = 0 ]; then
-		    echo "${b}ict$v compile errors in '$file' - no executable '$base' generated" >&2
+		    echo "${b}icc$v compile errors in '$file' - no executable '$base' generated" >&2
 		fi
 		let status+=1
 	    fi ;;
 	1)
 	    rm -f $base.c		# in case read only
-	    if nice ${b}ict$v $a $d -o $base.c -l $base.lst$l $file; then
+	    if nice ${b}icc$v $a $d -o $base.c -l $base.lst$l $file; then
 		list="$list $base.c"
 	    else
 		list="$list ERROR:$base.c"
@@ -166,9 +166,9 @@ for f in $*; do
 		base=${first%.*}
 		first=''		# -o applied only to first file
 	    fi
-	    if ! nice ${b}ict$v $d -c -l $base.lst$l $file; then
+	    if ! nice ${b}icc$v $d -c -l $base.lst$l $file; then
 		if [ "$q" = 0 ]; then
-		    echo "${b}ict$v compile errors in '$file'" >&2
+		    echo "${b}icc$v compile errors in '$file'" >&2
 		fi
 		let status+=1
 	    fi ;;
@@ -178,9 +178,9 @@ for f in $*; do
 		first=''		# -o applied only to first file
 	    fi
 	    rm -f $base.c
-	    if ! nice ${b}ict$v $d -o $base.c $file; then
+	    if ! nice ${b}icc$v $d -o $base.c $file; then
 		if [ "$q" = 0 ]; then
-		    echo "${b}ict$v compile errors in '$file'" >&2
+		    echo "${b}icc$v compile errors in '$file'" >&2
 		fi
 		let status+=1
 	    fi ;;
@@ -190,9 +190,9 @@ for f in $*; do
 		first=''
 	    fi
 	    rm -f $base.c
-	    if ! nice ${b}ict$v $d -o $base.c -l $base.lst$l $file; then
+	    if ! nice ${b}icc$v $d -o $base.c -l $base.lst$l $file; then
 		if [ "$q" = 0 ]; then
-		    echo "${b}ict$v compile errors in '$file'" >&2
+		    echo "${b}icc$v compile errors in '$file'" >&2
 		fi
 		let status+=1
 	    fi ;;
@@ -201,9 +201,9 @@ for f in $*; do
 		echo "output file '$first' ignored" >&2
 		first=''
 	    fi
-	    if ! nice ${b}ict$v $d -c $file; then
+	    if ! nice ${b}icc$v $d -c $file; then
 		if [ "$q" = 0 ]; then
-		    echo "${b}ict$v compile errors in '$file'" >&2
+		    echo "${b}icc$v compile errors in '$file'" >&2
 		fi
 		let status+=1
 	    fi ;;
@@ -244,12 +244,12 @@ if [ "$link" = 1 ]; then
 	fi
     else
 	if [ "$q" = 0 ]; then
-	    echo "${b}ict$v compile errors in '$list'" >&2
+	    echo "${b}icc$v compile errors in '$list'" >&2
 	fi
     fi
 fi
 
-# clean up temporary files generated by ict compiler unless -x option
+# clean up temporary files generated by icc compiler unless -x option
 if [ "$x" != 1 ]; then
     rm -f _list1.h _list2.h _list_.c
 fi
