Major overhaul of the iC make system
Makefile.in  22 'make' without arguments makes nothing - outputs a help message to use "m"
                do not output command lines - only errors and warnings
cons.y       22 fix bug in yyerror() for building test compiler 'cons' with option TESTCONS
iCpiI2c.c    62 output Allocation Table with T command
                make all I/O trace outputs the same format
             63 add hex value of actual pin output to I/O traces (differs when inverted)
lmain.c       6 make file * yyin and yyout extern for test C compiler (in line with gram.y)
m             9 major overhaul of the iC make system
makeAll      10 major overhaul of the iC make system
                now works as expected without several mysterious repeats
makeAll      11 correction for making Raspberry Pi drivers correctly
                and to ignore them on other systems
pifacecad.c   3 change #include <mcp23s17.s> to #include "mcp23s17.s"

    Id: src/Makefile.in 1.84
    Id: src/cons.y 1.8
    Id: src/iCpiI2C.c 1.8
    Id: src/lmain.c 1.21
    Id: src/m 1.27
    Id: src/makeAll 1.50
    Id: src/pifacecad.c 1.5

diff --git a/src/m b/src/m
--- a/src/m
+++ b/src/m
@@ -2,42 +2,45 @@
 
 usage()
 {
-    echo "Make iC components immcc and libict.a for debugging and optionally install them" >&2
-    echo "Usage $name[ -clSGPVXrtNmgpuedsyzIih][ -D<OPT>][ -W<OPT>][[ <iCmake_options>] <iC_sources>]" >&2
-    echo '		with no clSPrtm flags make immcc, libict.a and libict.so' >&2
-    echo '	-c	make immediate C compiler immcc' >&2
-    echo '	-l	make immediate C static library libict.a' >&2
-    echo '	-S	make immediate C shared library libict.so' >&2
-    echo '	-G	make goserver if golang is installed' >&2
-    echo '	-P	make iCpiFace for RASPBERRYPI PiFace with YYDEBUG only' >&2
-    echo '	-V	make iCpiPWM for RASPBERRYPI as SUID PWM and serVo program' >&2
-    echo '	-X	make iCpiI2C for RASPBERRYPI PiFace with YYDEBUG only' >&2
+    echo "Make various iC components for DEBUGGING and optionally install them" >&2
+    echo "Usage $name[ -aclSGPVXrtNmgpuedsyzIih][ -D<OPT>][ -W<OPT>][[ <iCmake_options>] <iC_sources>]" >&2
+    echo '		with no option flags make immcc, libict.a and install them' >&2
+    echo '	-a	make all - immcc, libict.a, libict.so and install' >&2
+    echo '		also make goserver and immag (replacements for iCserver andd immac) if golang' >&2
+    echo '		as well as iCpiFace, iCpiPUD, iCpiPWM, and iCpiI2C if on a Raspberry Pi' >&2
+    echo '	-c	make immediate C compiler immcc with YYDEBUG' >&2
+    echo '	-l	make immediate C static library libict.a with YYDEBUG' >&2
+    echo '	-S	make immediate C shared library libict.so WITHOUT YYDEBUG' >&2
+    echo '	-G	make goserver and immag (replacements for iCserver and immac) if golang' >&2
+    echo '	-P	make iCpiFace and iCpiPUD for Raspberry Pi with YYDEBUG' >&2
+    echo '	-V	make iCpiPWM for Raspberry Pi as SUID PWM and serVo program' >&2
+    echo '	-X	make iCpiI2C and iCpiPUD for Raspberry Pi with YYDEBUG' >&2
     echo '	-r	make standalone interpreter icr' >&2
     echo '	-t	make standalone interpreter ict' >&2
     echo '	-N	make const test internal constant expression compiler only' >&2
-    echo '	-m	make standalone internal C compiler lmain' >&2
+    echo '	-m	make standalone internal C compiler lmain for test' >&2
+    echo '    Extra options' >&2
     echo '	-g	compile for debugging and no optimisation (default -O2)' >&2
     echo '	-p	compile and link for profiling with gprof (-pg)' >&2
     echo '	-u	make any compiler targets with Symbol SYUNION option' >&2
     echo '	-e	make all targets with EFENCE option and link with -lefence' >&2
     echo '	-d	make with DEQ - double ended queues are slightly faster' >&2
-    echo '	-s	make with INT_MAX=32767' >&2
-    echo '		(on a 16 bit system INT_MAX is 32767 and -s is not required)' >&2
+    echo '	-s	make with INT_MAX=32767 (on a 16 bit system -s is not required)' >&2
     echo '		simulates compilation for a 16 bit system, which does' >&2
     echo '		no 32 bit arithmetic and rejects QL.. and IL.. I/O unless' >&2
-    echo '	-y	make with LONG16' >&2
+    echo '	-y	make with LONG16 (useful for a 16 bit system)' >&2
     echo '		produces code for long int arithmetic on a 16 bit system' >&2
-    echo '	-z	echo compiler calls with all options for debugging' >&2
     echo '	-D<OPT>	make all targets with <OPT> defined' >&2
     echo '	-W<OPT>	compile all C sources with -W<OPT> (useful for -Wall)' >&2
+    echo '	-z	echo compiler calls with all options for debugging' >&2
     echo "	-I	execute chmod +s /usr/bin/install /usr/bin/ranlib as su once" >&2
     echo "		this is required to run make install as an ordinary user" >&2
-    echo '	-i	make install after ./makeAll' >&2
+    echo '	-i	make install after programs have been updated' >&2
     echo '	-h	this help text' >&2
     echo '	NOTE: if any option is changed, make clean is automatically executed' >&2
     echo "	<iC_sources>  list of iC source files which will be made with iCmake" >&2
     echo 'Author:	John E. Wulff        <immediateC@gmail.com>' >&2
-    echo '$Id: m 1.26 $' >&2
+    echo '$Id: m 1.27 $' >&2
 }
 
 name=${0##*/}
@@ -50,15 +53,30 @@ P=''
 G=''
 V=''
 X=''
+I=''
 z=0
 o=''
 
-while getopts ":clSNPGVXrtmgpudsyezD:W:Iih" opt; do
+if [ -x /bin/uname ]; then
+    cpu=`/bin/uname -m`
+    tail=${cpu#"armv"}
+    if [[ "$cpu" != "$tail" ]]; then
+	o=" OPT=\"-DRASPBERRYPI\""
+    fi
+fi
+
+while getopts ":aclSNPGVXrtmgpudsyezD:W:Iih" opt; do
     case $opt in
+    a ) clSGrtm="${clSGrtm}clSuG";
+	if [ -n "$o" ]; then
+	    clSGrtm="${clSGrtm}PVX";
+	fi
+	i="install";;
     c ) clSGrtm="${clSGrtm}c";;
     l ) clSGrtm="${clSGrtm}l";;
     S ) clSGrtm="${clSGrtm}S";;
     G ) clSGrtm="${clSGrtm}G";;
+    N ) clSGrtm="${clSGrtm}N";;
     r ) clSGrtm="${clSGrtm}r";;
     t ) clSGrtm="${clSGrtm}t";;
     m ) clSGrtm="${clSGrtm}m";;
@@ -75,15 +93,8 @@ while getopts ":clSNPGVXrtmgpudsyezD:W:Iih" opt; do
     N ) N="N";;
     P ) P="P";;
     V ) V="V";;
-    X ) X="X";echo "option X";;
-    I )
-	echo "Enter root:" >&2
-	sudo chmod +s /usr/bin/install /usr/bin/ranlib
-	echo "chmod +s /usr/bin/install /usr/bin/ranlib" >&2
-	echo "Exit  root:" >&2
-	sudo -k
-	exit
-	;;
+    X ) X="X";;
+    I ) I="I";;
     i )	i="install";;
     h )	usage; exit 127;;
     \?)	echo "$name: illegal option '-$OPTARG'"; usage; exit 127;;
@@ -91,11 +102,26 @@ while getopts ":clSNPGVXrtmgpudsyezD:W:Iih" opt; do
 done
 shift $(($OPTIND - 1))
 
-if [ -n "$N" -o -n "$P" -o -n "$G" -o -n "$V" -o -n "$X" ]; then
-    echo "### make Const and/or iCpiFace and/or iCgpioPUD and/or iCpiPWM and/or iCpiI2C"
-    ./makeAll -qg$N$P$G$V$X$gpudsyez$dw
-elif [ -z "$clSGrtm" ]; then
-    clSGrtm="cl"
+if [ -n "$I" ]; then
+    echo "Enter root:" >&2
+    sudo chmod +s /usr/bin/install /usr/bin/ranlib
+    echo "chmod +s /usr/bin/install /usr/bin/ranlib" >&2
+    echo "Exit  root:" >&2
+fi
+
+if [ -n "$P" ]; then
+    clSGrtm="${clSGrtm}P"
+fi
+if [ -n "$V" ]; then
+    clSGrtm="${clSGrtm}V"
+fi
+if [ -n "$X" ]; then
+    clSGrtm="${clSGrtm}X"
+fi
+
+if [ -z "$clSGrtm" -a -z "$i" ]; then
+    clSGrtm="clSu"
+    i="install"
 fi
 
 if [ -n "$clSGrtm" ]; then
@@ -104,15 +130,11 @@ if [ -n "$clSGrtm" ]; then
 fi
 
 if [ -n "$i" ]; then
-    if [ -x /bin/uname ]; then
-	cpu=`/bin/uname -m`
-	tail=${cpu#"armv"}
-	if [[ "$cpu" != "$tail" ]]; then
-	    echo "### make iCpiFace, iCpiPUD, iCpiI2C and iCpiPWM"
-	    ./makeAll -qgPVX$gpudsyez$dw
-	    o=" OPT=\"-DRASPBERRYPI\""
-	fi
-    fi
     echo "### make$o install"
     make$o install
 fi
+
+for ic; do
+    echo "iCmake -As $ic"
+    iCmake -As $ic
+done
diff --git a/src/makeAll b/src/makeAll
--- a/src/makeAll
+++ b/src/makeAll
@@ -41,6 +41,7 @@ usage ()
     echo '	-P	make iCpiFace real SIO digital I/O for RASPBERRYPI, YYDEBUG only' >&2
     echo '		   + iCgpioPUD for RASPBERRYPI as SUID auxiliary program' >&2
     echo '	-X	make iCpiI2C real I2C digital I/O for RASPBERRYPI, YYDEBUG only' >&2
+    echo '		   + iCgpioPUD for RASPBERRYPI as SUID auxiliary program' >&2
     echo '	-V	make iCpiPWM real analog I/O for RASPBERRYPI, PWM, serVo and ADC' >&2
     echo '	-R	make icr only without modifying cexe.c' >&2
     echo '	-T	make ict only without modifying cexe.c' >&2
@@ -62,7 +63,7 @@ usage ()
     echo '	-z	echo compiler calls with all options for debugging (not -q)' >&2
     echo '	-h	this help text' >&2
     echo '	NOTE: if any option is changed, make clean is automatically executed' >&2
-    echo '	$Id: makeAll 1.49 $' >&2
+    echo '	$Id: makeAll 1.50 $' >&2
 }
 
 makeLib ()
@@ -161,62 +162,46 @@ makeLmain ()
 
 makePiFace ()
 {
-    if [[ -n "$raspberrypi" ]]; then
-	mv misc.$O icend.$O tcpc.$O rpi_gpio.$O mcp23s17.$O pifacecad.$O Make_tmp 2> /dev/null
-	if [ -d PiFaceObjs ]; then
-	    mv PiFaceObjs/* .
-	else
-	    mkdir PiFaceObjs
-	fi
-	make OPT="-DTCP -DYYDEBUG$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCpiFace
-	mv misc.$O icend.$O tcpc.$O rpi_gpio.$O mcp23s17.$O pifacecad.$O PiFaceObjs
-	mv Make_tmp/* . 2> /dev/null
+    mv misc.$O icend.$O tcpc.$O rpi_gpio.$O mcp23s17.$O pifacecad.$O Make_tmp 2> /dev/null
+    if [ -d PiFaceObjs ]; then
+	mv PiFaceObjs/* .
     else
-	echo "Error makeAll -P: cannot make iCpiFace for a '$cpu' cpu - only for an 'armv*' on a Raspberry Pi"
+	mkdir PiFaceObjs
     fi
+    make OPT="-DTCP -DYYDEBUG$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCpiFace
+    mv misc.$O icend.$O tcpc.$O rpi_gpio.$O mcp23s17.$O pifacecad.$O PiFaceObjs
+    mv Make_tmp/* . 2> /dev/null
 }
 
 makePiI2C ()
 {
-    if [[ -n "$raspberrypi" ]]; then
-	mv misc.$O icend.$O tcpc.$O rpi_gpio.$O mcp23s17.$O pifacecad.$O Make_tmp 2> /dev/null
-	if [ -d PiI2CObjs ]; then
-	    mv PiI2CObjs/* .
-	else
-	    mkdir PiI2CObjs
-	fi
-	make OPT="-DTCP -DYYDEBUG$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCpiI2C
-	mv misc.$O icend.$O tcpc.$O rpi_gpio.$O mcp23s17.$O pifacecad.$O PiI2CObjs
-	mv Make_tmp/* . 2> /dev/null
+    mv misc.$O icend.$O tcpc.$O rpi_gpio.$O Make_tmp 2> /dev/null
+    if [ -d PiI2CObjs ]; then
+	mv PiI2CObjs/* .
     else
-	echo "Error makeAll -P: cannot make iCpiI2C for a '$cpu' cpu - only for an 'armv*' on a Raspberry Pi"
+	mkdir PiI2CObjs
     fi
+    make OPT="-DTCP -DYYDEBUG$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCpiI2C
+    mv misc.$O icend.$O tcpc.$O rpi_gpio.$O PiI2CObjs
+    mv Make_tmp/* . 2> /dev/null
 }
 
 makeGpioPUD ()
 {
-    if [[ -n "$raspberrypi" ]]; then
-	make OPT="$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCgpioPUD
-    else
-	echo "Error makeAll -P: cannot make iCgpioPUD for a '$cpu' cpu - only for an 'armv*' on a Raspberry Pi"
-    fi
+    make OPT="$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCgpioPUD
 }
 
 makePiPWM ()
 {
-    if [[ -n "$raspberrypi" ]]; then
-	mv misc.$O icend.$O tcpc.$O rpi_rev.$O Make_tmp 2> /dev/null
-	if [ -d PiPWMObjs ]; then
-	    mv PiPWMObjs/* .
-	else
-	    mkdir PiPWMObjs
-	fi
-	make OPT="-DPWM -DTCP -DYYDEBUG$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCpiPWM
-	mv misc.$O icend.$O tcpc.$O rpi_rev.$O PiPWMObjs
-	mv Make_tmp/* . 2> /dev/null
+    mv misc.$O icend.$O tcpc.$O rpi_rev.$O Make_tmp 2> /dev/null
+    if [ -d PiPWMObjs ]; then
+	mv PiPWMObjs/* .
     else
-	echo "Error makeAll -V: cannot make iCpiPWM for a '$cpu' cpu - only for an 'armv*' on a Raspberry Pi"
+	mkdir PiPWMObjs
     fi
+    make OPT="-DPWM -DTCP -DYYDEBUG$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCpiPWM
+    mv misc.$O icend.$O tcpc.$O rpi_rev.$O PiPWMObjs
+    mv Make_tmp/* . 2> /dev/null
 }
 
 q=""
@@ -230,18 +215,17 @@ d=""
 e=""
 s=""
 y=""
-C=0
-L=0
-S=0
-G=0
-P=0
-X=0
-V=0
-R=0
-T=0
-N=0
-M=0
-IM_LIB=1
+C=""
+L=""
+S=""
+G=""
+P=""
+X=""
+V=""
+R=""
+T=""
+N=""
+M=""
 cflags="-O2"			# optimisation, no debugging info
 ldflags=""			# no profiling
 O="o"
@@ -258,15 +242,15 @@ while getopts ":qgpclrtmCLSPXGVRTNMuedsyzhD:W:o:" opt; do
     q )	q="q";;		# echo only - dont kill
     g )	cflags="-g";;	# debugging, no optimisation
     p )	ldflags=" -pg";;	# profiling
-    c )	C=1; IM_LIB=0; c="-DYYDEBUG"; YN=$(($YN|1));;
-    l )	L=1; IM_LIB=0; l=" -DYYDEBUG"; YN=$(($YN|2));;
-    r )	R=1; IM_LIB=0; r=" -DYYDEBUG";;
-    t )	T=1; IM_LIB=0; t=" -DYYDEBUG";;
-    m )	M=1; IM_LIB=0; m=" -DYYDEBUG";;
-    C )	C=1; IM_LIB=0;;
-    L )	L=1; IM_LIB=0;;
-    S )	S=1; IM_LIB=0;;
-    G )	G=1; IM_LIB=0;;
+    c )	C=1; c="-DYYDEBUG"; YN=1;;
+    l )	L=1; l=" -DYYDEBUG"; YN=1;;
+    r )	R=1; r=" -DYYDEBUG";;
+    t )	T=1; t=" -DYYDEBUG";;
+    m )	M=1; m=" -DYYDEBUG";;
+    C )	C=1;;
+    L )	L=1;;
+    S )	S=1;;
+    G )	G=1;;
     P )	P=1;;
     X )	X=1;;
     V )	V=1;;
@@ -308,77 +292,101 @@ fi
 if [ $YN -ne 0 ]; then
     Y=" -DYYDEBUG=$YN"
 fi
-if [ $P -eq 0 ] && [ $X -eq 0 ] && [ $V -eq 0 ] && ! perl icg.pl $Y$u$d$e$o$s$y icc.h | cmp -s - icg.h; then
+if [ ! -f icg.h ] || ( ( [ -n "$C" ] || [ -n "$L" ] ) && ! perl icg.pl $Y$u$d$e$o$s$y icc.h | cmp -s - icg.h ); then
     echo "Options changed to '$Y$u$d$e$o$s$y'"
-    if [ $R -eq 0 ] && [ $T -eq 0 ]; then
+    if [ -z "$R" ] && [ -z "$T" ]; then
 	echo "   make clean"
 	make clean 2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
     fi
     echo "   remake icg.h"
     perl icg.pl $Y$u$d$e$o$s$y icc.h > icg.h
+    S=1;
+    if [[ -n "$raspberrypi" ]]; then
+	P=1;
+	X=1;
+	V=1;
+    fi
 fi
 
-if [ $IM_LIB = 1 ] || [ $C = 1 ]; then
+if [ -n "$C" ]; then
     echo "make OPT=\"$c$u$d$e$o$s$y\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" immcc"
     make OPT="$c$u$d$e$o$s$y" CFLAGS="$cflags" LDFLAGS="$ldflags" immcc 2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
-if [ $IM_LIB = 1 ] || [ $L = 1 ]; then		# echo must be before makeLib call - output is redirected - same for others
+if [ -n "$L" ]; then		# echo must be before makeLib call - output is redirected - same for others
     echo "make OPT=\"-DLOAD -DTCP$l$d$e$o$s$y\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" libict.a"
     makeLib  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
-if [ $IM_LIB = 1 ] || [ $S = 1 ]; then
+if [ -n "$S" ]; then
     if [ "${OSTYPE%-*}" = "linux" ]; then
 	echo "make OPT=\"-fPIC -DLOAD -DTCP$d$e$o$s$y\" CFLAGS=\"-O2$W\" libict.so"
 	makeShared  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
-    elif [ $IM_LIB != 1 ]; then
+    else
 	echo "ERROR: cannot make shared library libict.so on non linux systems"
     fi
 fi
 
-if [ $IM_LIB = 1 ] || [ $G = 1 ]; then
+if [ -n "$G" ]; then
     echo "make goserver"
     makeGOserver  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
     echo "make immag"
     makeGOimmag  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
-if [ $R = 1 ]; then
+if [ -n "$R" ]; then
     echo "make OPT=\"-DRUN$r$u$d$e$os$s$y\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" icr"
     makeIcr  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
-if [ $T = 1 ]; then
+if [ -n "$T" ]; then
     echo "make OPT=\"-DTCP$t$u$d$e$os$s$y\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" ict"
     makeIct  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
-if [ $N = 1 ]; then
+if [ -n "$N" ]; then
     echo "make OPT=\"-DTESTCONS$m$u$d$e$os$s$y\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" const"
     makeConst  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
-if [ $M = 1 ]; then
+if [ -n "$M" ]; then
     echo "make OPT=\"-DLMAIN$m$u$d$e$os$s$y\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" lmain"
     makeLmain  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
-if [ $P = 1 ]; then
-    echo "make OPT=\"-DTCP -DYYDEBUG$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCpiFace"
-    makePiFace  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
-    echo "make OPT=\"$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCgpioPUD"
-    makeGpioPUD  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+if [ -n "$P" ]; then
+    if [[ -n "$raspberrypi" ]]; then
+	echo "make OPT=\"-DTCP -DYYDEBUG$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCpiFace"
+	makePiFace  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+	if [[ iCgpioPUD -ot iCgpioPUD.c ]]; then
+	    echo "make OPT=\"$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCgpioPUD"
+	    makeGpioPUD  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+	fi
+    else
+	echo "Error makeAll -P: cannot make iCpiFace for a '$cpu' cpu - only for an 'armv*' on a Raspberry Pi"
+    fi
 fi
 
-if [ $V = 1 ]; then
-    echo "make OPT=\"-DPWM -DTCP -DYYDEBUG$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCpiPWM"
-    makePiPWM  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+if [ -n "$V" ]; then
+    if [[ -n "$raspberrypi" ]]; then
+	echo "make OPT=\"-DPWM -DTCP -DYYDEBUG$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCpiPWM"
+	makePiPWM  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+    else
+	echo "Error makeAll -V: cannot make iCpiPWM for a '$cpu' cpu - only for an 'armv*' on a Raspberry Pi"
+    fi
 fi
 
-if [ $X = 1 ]; then
-    echo "make OPT=\"-DTCP -DYYDEBUG$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCpiI2C"
-    makePiI2C  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+if [ -n "$X" ]; then
+    if [[ -n "$raspberrypi" ]]; then
+	echo "make OPT=\"-DTCP -DYYDEBUG$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCpiI2C"
+	makePiI2C  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+	if [[ iCgpioPUD -ot iCgpioPUD.c ]]; then
+	    echo "make OPT=\"$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCgpioPUD"
+	    makeGpioPUD  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+	fi
+    else
+	echo "Error makeAll -X: cannot make iCpiI2C for a '$cpu' cpu - only for an 'armv*' on a Raspberry Pi"
+    fi
 fi
 
 rmdir Make_tmp
