RCS	icc.v	1.118	2008/02/29 18:36:47
### Equivalent to V341
### Makefile.in		1.49
W340_02: introduce auxiliary source inic.c to make inic.o for libict.a and new inic.a
W340_04: add icend.c - new file definining default iCend() - complement to iCbegin()
	rename inic.o icbegin.o - inic.a icbegin.a
### README.tpl		1.17
W340_04: bring installation notes up to date
### comp.h		1.56
W340_01: introduce iC_Wflag - #define W_DEPRECATED_LOGIC 01 /* do/no logic warnings */
### comp.y		1.98
W340_01: introduce iC_Wflag - #define W_DEPRECATED_LOGIC 01 /* do/no logic warnings */
	use iC_Wflag as as iC_Pflag (pedantic -P) to issue these warnings
### iClive		1.41
W340_04: in build_file() execute iCmake with qx() rather than with system() to return STDERR
	grep STDERR output with '^*** ' to find out if there were Warnings - if yes
	switch to listing with *** marked, but search statistics suppressed
	if there were Errors, pick this up with $? and suppress search statistics as well
### iCmake		1.35
W340_01: add CFL="-g -fno-builin" to stop spurious warning for bessel function j0() etc
### icbegin.c		1.2
W340_02: new file definining default iniC() - initially called inic.c
W340_03: rename file definining default iCini() - previously iniC()
W340_04: rename inic.c - file definining default iCbegin() - previously iCini()
### icc.c		1.59
W340_01: introduce iC_Wflag - #define W_DEPRECATED_LOGIC 01 /* do/no logic warnings */
	-W[no-]<warn>   positive/negative warning options
	-Wno-deprecated-logic -Wno-deprecated -Wdeprecated (default)
### icc.h		1.65
W340_02: break up members gt_list and gt_rlist into union GppIpI gt_ll and gt_rll
	#define pseudo members for different union members to avoid casts
	declare iniC(void)
W340_03: rename iniC() iCini()
W340_04: rename iCini() iCbegin() - add function declaration iCend()
### icend.c		1.1
W340_04: new file definining default iCend() - complement to iCbegin()
### icr.c		1.34
W340_02: add call to iniC()
W340_03: rename call iCini() - rename EOP EOI
W340_04: rename iCini() iCbegin() - add function call iCend()
### ict.c		1.50
W340_02: add call to iniC()
W340_03: rename call iCini() - rename EOP EOI
W340_04: rename iCini() iCbegin() - add function call iCend()
### makeAll		1.27
W340_02: remove -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast - not known in gcc 3.3.5
	replace by unions in icc.h
	fix analysis of -W flag
W340_03: change option -z to -y; add -z to echo compiler calls
### manifest		1.14
W340_04: doc/ delete iC.doc iC.sxw; add iC.pdf iC.odt; src/ add bar.ic hello.ic simple.ic
	add icbegin.c icend.c
### outp.c		1.87
W340_02: break up members gt_list and gt_rlist into union GppIpI gt_ll and gt_rll
	make fp type GppIpI instead of Gate** to utilise union to avoid cast
### rsff.c		1.47
W340_02: break up members gt_list and gt_rlist into union GppIpI gt_ll and gt_rll
	use pseudo members gt_functn and gt_listn
### scan.c		1.34
W340_02: break up members gt_list and gt_rlist into union GppIpI gt_ll and gt_rll
	use pseudo member gt_functn

CVS-ID: src/Makefile.in 1.49
CVS-ID: src/README.tpl 1.17
CVS-ID: src/comp.h 1.56
CVS-ID: src/comp.y 1.98
CVS-ID: src/iClive 1.41
CVS-ID: src/iCmake 1.35
CVS-ID: src/icbegin.c 1.2
CVS-ID: src/icc.c 1.59
CVS-ID: src/icc.h 1.65
CVS-ID: src/icc.v 1.118
CVS-ID: src/icend.c 1.1
CVS-ID: src/icr.c 1.34
CVS-ID: src/ict.c 1.50
CVS-ID: src/makeAll 1.27
CVS-ID: src/manifest 1.14
CVS-ID: src/outp.c 1.87
CVS-ID: src/rsff.c 1.47
CVS-ID: src/scan.c 1.34

diff --git a/src/makeAll b/src/makeAll
--- a/src/makeAll
+++ b/src/makeAll
@@ -22,7 +22,7 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/}' [-qgclrtmdeCLRTMszh] [-D<OPT>] [-o<OBJ>]' >&2
+    echo 'Usage:	'${0##*/}' [-qgclrtmdeCLRTMsyh] [-D<OPT>] [-o<OBJ>]' >&2
     echo '	call make for immcc, libict.a, icr, ict and lmain with correct options' >&2
     echo '	-q	output only headings and error messages' >&2
     echo '	-g	compile for debugging and no optimisation (default -O2)' >&2
@@ -47,11 +47,12 @@ usage ()
     echo '		(on a 16 bit system INT_MAX is 32767 and -s is not required)' >&2
     echo '		simulates compilation for a 16 bit system, which does' >&2
     echo '		no 32 bit arithmetic and rejects QL.. and IL.. I/O unless' >&2
-    echo '	-z	make with -DLONG16        (make clean required first)' >&2
+    echo '	-y	make with -DLONG16        (make clean required first)' >&2
     echo '		produces code for long int arithmetic on a 16 bit system' >&2
     echo '	-o<OBJ>	define object extension (o is default; obj for Windows)' >&2
+    echo '	-z	echo compiler calls with all options for debugging (not -q)' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: makeAll,v 1.26 2008/02/13 19:46:07 jw Exp $' >&2
+    echo '	$Id: makeAll,v 1.27 2008/02/24 22:45:06 jw Exp $' >&2
 }
 
 makeLib ()
@@ -62,7 +63,7 @@ makeLib ()
     else
 	mkdir LibObjs
     fi
-    make OPT="-DLOAD -DTCP$l$d$e$o$s$z" CFLAGS="$cflags" libict.a
+    make OPT="-DLOAD -DTCP$l$d$e$o$s$y" CFLAGS="$cflags" libict.a
     mv ict.$O misc.$O link.$O rsff.$O scan.$O tcpc.$O  LibObjs
     mv Make_tmp/* . 2> /dev/null
 }
@@ -75,7 +76,7 @@ makeIcr ()
     else
 	mkdir IcrObjs
     fi
-    make OPT="-Wno-pointer-to-int-cast -Wno-int-to-pointer-cast -DRUN$r$u$d$e$o$s$z" CFLAGS="$cflags" icr
+    make OPT="-DRUN$r$u$d$e$o$s$y" CFLAGS="$cflags" icr
     mv comp.$O genr.$O gram.$O icr.$O misc.$O init.$O lexc.$O link.$O icc.$O outp.$O rsff.$O scan.$O symb.$O IcrObjs
     mv Make_tmp/* . 2> /dev/null
 }
@@ -88,7 +89,7 @@ makeIct ()
     else
 	mkdir IctObjs
     fi
-    make OPT="-Wno-pointer-to-int-cast -Wno-int-to-pointer-cast -DTCP$t$u$d$e$o$s$z" CFLAGS="$cflags" ict
+    make OPT="-DTCP$t$u$d$e$o$s$y" CFLAGS="$cflags" ict
     mv comp.$O genr.$O gram.$O ict.$O misc.$O init.$O lexc.$O link.$O icc.$O outp.$O rsff.$O scan.$O symb.$O tcpc.$O IctObjs
     mv Make_tmp/* . 2> /dev/null
 }
@@ -101,7 +102,7 @@ makeLmain ()
     else
 	mkdir LmainObjs
     fi
-    make OPT="-DLMAIN$m$u$d$e$o$s$z" CFLAGS="$cflags" lmain
+    make OPT="-DLMAIN$m$u$d$e$o$s$y" CFLAGS="$cflags" lmain
     mv misc.$O gram.$O lexc.$O LmainObjs
     mv Make_tmp/* . 2> /dev/null
 }
@@ -116,7 +117,7 @@ u=""
 d=""
 e=""
 s=""
-z=""
+y=""
 C=0
 L=0
 R=0
@@ -127,11 +128,12 @@ cflags="-O2"			# optimisation, no debugging info
 O="o"
 o=""
 w=""
+z=0
 
-while getopts ":qgclrtmCLRTMudeD:W:szo:h" opt; do
+while getopts ":qgclrtmCLRTMudeD:W:syo:zh" opt; do
     case $opt in
-    q )	q=1;;		# echo only - dont kill
-    g )	cflags="-g$w";;	# debugging, no optimisation
+    q )	q="q";;		# echo only - dont kill
+    g )	cflags="-g";;	# debugging, no optimisation
     c )	C=1; IM_LIB=0; c="-DYYDEBUG";;
     l )	L=1; IM_LIB=0; l=" -DYYDEBUG";;
     r )	R=1; IM_LIB=0; r=" -DYYDEBUG";;
@@ -146,14 +148,16 @@ while getopts ":qgclrtmCLRTMudeD:W:szo:h" opt; do
     d )	d=" -DDEQ";;
     e )	e=" -DEFENCE";;
     D ) o=" -D$OPTARG";;
-    W ) w=" -W$OPTARG"; if [ -n "$cflags" ]; then cflags="$cflags$w"; fi ;;
+    W ) w=" -W$OPTARG";;
     s )	s=" -DINT_MAX=32767";;
-    z )	z=" -DLONG16";;
+    y )	y=" -DLONG16";;
     o ) O="$OPTARG";;
+    z )	z=1; q="";;
     h )	usage; exit 255;;
     \?)	echo "$name: illegal option '-$OPTARG'"; usage; exit 127;;
     esac
 done
+cflags="$cflags$w";
 shift $(($OPTIND - 1))
 
 if [ -f Make_tmp ]; then
@@ -162,31 +166,33 @@ if [ -f Make_tmp ]; then
 fi
 test -d Make_tmp || mkdir Make_tmp;
 
-rm -f icg.h
-perl icg.pl $d$s$z icc.h > icg.h
+if [ $z -eq 1 ]; then
+    echo "rm -f icg.h; perl icg.pl $d$s$y icc.h > icg.h" >&2
+fi
+rm -f icg.h; perl icg.pl $d$s$y icc.h > icg.h
 
 if [ $IM_LIB = 1 ] || [ $C = 1 ]; then
-    echo "make OPT=\"$c$u$d$e$o$s$z\" CFLAGS=\"$cflags\" immcc"
-    make OPT="$c$u$d$e$o$s$z" CFLAGS="$cflags" immcc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+    echo "make OPT=\"$c$u$d$e$o$s$y\" CFLAGS=\"$cflags\" immcc"
+    make OPT="$c$u$d$e$o$s$y" CFLAGS="$cflags" immcc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $IM_LIB = 1 ] || [ $L = 1 ]; then
-    echo "make OPT=\"-DLOAD -DTCP$l$d$e$o$s$z\" CFLAGS=\"$cflags\" libict.a"
+    echo "make OPT=\"-DLOAD -DTCP$l$d$e$o$s$y\" CFLAGS=\"$cflags\" libict.a"
     makeLib  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $R = 1 ]; then
-    echo "make OPT=\"-DRUN$r$u$d$e$o$s$z\" CFLAGS=\"$cflags\" icr"
+    echo "make OPT=\"-DRUN$r$u$d$e$o$s$y\" CFLAGS=\"$cflags\" icr"
     makeIcr  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $T = 1 ]; then
-    echo "make OPT=\"-DTCP$t$u$d$e$o$s$z\" CFLAGS=\"$cflags\" ict"
+    echo "make OPT=\"-DTCP$t$u$d$e$o$s$y\" CFLAGS=\"$cflags\" ict"
     makeIct  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $M = 1 ]; then
-    echo "make OPT=\"-DLMAIN$m$u$d$e$o$s$z\" CFLAGS=\"$cflags\" lmain"
+    echo "make OPT=\"-DLMAIN$m$u$d$e$o$s$y\" CFLAGS=\"$cflags\" lmain"
     makeLmain  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
@@ -201,7 +207,7 @@ exit 0
 
 =head1 SYNOPSIS
 
-    makeAll [-qgclrtmdeCLRTMszh] [-D<OPT>] [-o<OBJ>]
+    makeAll [-qgclrtmdeCLRTMsyh] [-D<OPT>] [-o<OBJ>]
     call make for immcc, libict.a, icr, ict and lmain with correct options
     -q      output only headings and error messages
     -g      compile for debugging and no optimisation (default -O2)
@@ -225,9 +231,10 @@ exit 0
             (on a 16 bit system INT_MAX is 32767 and -s is not required)
             simulates compilation for a 16 bit system, which does
             no 32 bit arithmetic and rejects QL.. and IL.. I/O unless
-    -z      make with -DLONG16        (make clean required first)
+    -y      make with -DLONG16        (make clean required first)
             produces code for long int arithmetic on a 16 bit system
     -o<OBJ> define object extension (o is default; obj for Windows)
+    -z      echo compiler calls with all options for debugging (not -q)
     -h      this help text
 
 =head1 DESCRIPTION
