RCS	pplc.v	1.46	2001/01/13 17:47:16
make cexe.c for -c with alias corrections - fix pplstfix

CVS-ID: src/comp.y 1.37
CVS-ID: src/genr.c 1.28
CVS-ID: src/main.c 1.13
CVS-ID: src/makeload 1.5
CVS-ID: src/outp.c 1.28
CVS-ID: src/pplc.v 1.46
CVS-ID: src/pplstfix 1.4

diff --git a/src/makeload b/src/makeload
--- a/src/makeload
+++ b/src/makeload
@@ -4,12 +4,15 @@
 #
 #	make the load.a lib with OPT=LOAD
 #
-#	$Id: makeload,v 1.4 2000/06/10 11:27:58 jw Exp $
+#	$Id: makeload,v 1.5 2001/01/11 18:42:26 jw Exp $
 #
 ########################################################################
 
-if [[ -e Make_tmp ]]; then echo 'Make_tmp exists ??? - nothing made'; exit 1; fi
-mkdir Make_tmp
+if [[ -f Make_tmp ]]; then
+    echo 'Error makeload: Make_tmp exists as file ??? - nothing made' >&2
+    exit 1;
+fi
+test -d Make_tmp || mkdir Make_tmp;
 mv pptc.o link.o rsff.o scan.o Make_tmp
 if [[ -d LoadObjs ]]; then
     mv LoadObjs/* .
