RCS	makex	1.10	intermediate version
use the name icc instead of pplc throughout the project

CVS-ID: src/makex 1.10

diff --git a/src/makex b/src/makex
--- a/src/makex
+++ b/src/makex
@@ -14,14 +14,14 @@ usage ()
     echo '	-s	supress C output and executable, listing only' >&2
     echo '	-c	generate C output only' >&2
     echo '	-b	generate both listing and C output' >&2
-    echo '	-n	generate no output, report pplc compile errors only' >&2
+    echo '	-n	generate no output, report icc compile errors only' >&2
     echo '		-s and -n generate cexe.c for last file as a side effect' >&2
-    echo '	-v<N>	use pplc<N> eg pplc1 pplc2 ...' >&2
+    echo '	-v<N>	use icc<N> eg icc1 icc2 ...' >&2
     echo '	-6	produce logic generation listing file.lst6' >&2
     echo '		default listing is file.lst' >&2
     echo '	-A	compile output ARITHMETIC ALIAS nodes' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: makex,v 1.9 2001/02/20 18:03:47 jw Exp $' >&2
+    echo '	$Id: makex,v 1.10 2001/02/21 16:21:41 jw Exp $' >&2
 }
 
 link=0
@@ -65,7 +65,7 @@ for f in $*; do
     file=$f
     base=${file%.*}
     if [[ $file = $base ]]; then
-	file="$base.p"
+	file="$base.ic"
     fi
     if [[ ! -f $file ]]; then
 	echo "iC file $file does not exist" >&2
@@ -77,16 +77,16 @@ for f in $*; do
     case $link in
     0)
 	rm -f $base.c $base
-	if nice pplc$v $d -o $base.c -l $base.lst$l $file; then
-	    if nice gcc -g -DYYDEBUG -o $base $base.c list.c load$v.a; then
+	if nice icc$v $d -o $base.c -l $base.lst$l $file; then
+	    if nice gcc -g -DYYDEBUG -o $base $base.c list.c ict$v.a; then
 		$base -d540 > $base.ini
 	    fi
 	else
-	    echo "pplc$v compile errors in '$file' - no executable '$base' generated" >&2
+	    echo "icc$v compile errors in '$file' - no executable '$base' generated" >&2
 	fi ;;
     1)
 	rm -f $base.c
-	if nice pplc$v $a $d -o $base.c -l $base.lst$l $file; then
+	if nice icc$v $a $d -o $base.c -l $base.lst$l $file; then
 	    list="$list $base.c"
 	else
 	    list="$list ERROR:$base.c"
@@ -97,22 +97,22 @@ for f in $*; do
 	    a="-a"
 	fi ;;
     2)
-	if ! nice pplc$v $d -c -l $base.lst$l $file; then
-	    echo "pplc$v compile errors in '$file'" >&2
+	if ! nice icc$v $d -c -l $base.lst$l $file; then
+	    echo "icc$v compile errors in '$file'" >&2
 	fi ;;
     3)
 	rm -f $base.c
-	if ! nice pplc$v -o $base.c $file; then
-	    echo "pplc$v compile errors in '$file'" >&2
+	if ! nice icc$v -o $base.c $file; then
+	    echo "icc$v compile errors in '$file'" >&2
 	fi ;;
     4)
 	rm -f $base.c
-	if ! nice pplc$v $d -o $base.c -l $base.lst$l $file; then
-	    echo "pplc$v compile errors in '$file'" >&2
+	if ! nice icc$v $d -o $base.c -l $base.lst$l $file; then
+	    echo "icc$v compile errors in '$file'" >&2
 	fi ;;
     5)
-	if ! nice pplc$v -c $file; then
-	    echo "pplc$v compile errors in '$file'" >&2
+	if ! nice icc$v -c $file; then
+	    echo "icc$v compile errors in '$file'" >&2
 	fi ;;
     esac
 done
@@ -121,10 +121,10 @@ if [[ $link = 1 ]]; then
     if [[ $flag = noerror ]]; then
 	rm -f $first
 	echo "link $first from$list"
-	if nice gcc -g -DYYDEBUG -o $first $list list.c load$v.a; then
+	if nice gcc -g -DYYDEBUG -o $first $list list.c ict$v.a; then
 	    $first -d540 > $first.ini
 	fi
     else
-	echo "pplc$v compile errors in '$list'" >&2
+	echo "icc$v compile errors in '$list'" >&2
     fi
 fi
