RCS	icc.v	1.63	2001/03/18 14:04:32
change from /usr/bin/ksh to /bin/sh for all shell scripts
use if [ ... ] instead of if [[ ... ]] for old sh
allow execution without . in PATH (su can make)

CVS-ID: src/ICMake 1.16
CVS-ID: src/Makefile.in 1.18
CVS-ID: src/README 1.4
CVS-ID: src/icc.v 1.63
CVS-ID: src/load.c 1.22
CVS-ID: src/main.c 1.20
CVS-ID: src/makeAll 1.9
CVS-ID: src/makeIct 1.6
CVS-ID: src/makeLib 1.10
CVS-ID: src/perlinstall 1.5

diff --git a/src/makeLib b/src/makeLib
--- a/src/makeLib
+++ b/src/makeLib
@@ -10,24 +10,24 @@
 #   For more information about this program, or for information on how
 #   to contact the author, see the README file or <john.wulff@inka.de>
 #
-#	make ict with OPT=TCP
+#	make the libict.a library with OPT=LOAD
 #
-#	$Id: makeIct,v 1.6 2001/03/18 14:03:15 jw Exp $
+#	$Id: makeLib,v 1.10 2001/03/18 14:03:15 jw Exp $
 #
 ########################################################################
 
 if [ -f Make_tmp ]; then
-    echo 'Error makeIct: Make_tmp exists as file ??? - nothing made' >&2
+    echo 'Error makeload: Make_tmp exists as file ??? - nothing made' >&2
     exit 1;
 fi
 test -d Make_tmp || mkdir Make_tmp;
-mv main.o Make_tmp
-if [ -d PptcObjs ]; then
-    mv PptcObjs/* .
+mv link.o rsff.o scan.o Make_tmp
+if [ -d LoadObjs ]; then
+    mv LoadObjs/* .
 else
-    mkdir PptcObjs
+    mkdir LoadObjs
 fi
-make OPT='-DTCP' ict
-mv main.o ict.o PptcObjs
+make OPT='-DLOAD -DTCP' libict.a
+mv ict.o link.o rsff.o scan.o LoadObjs
 mv Make_tmp/* .
 rmdir Make_tmp
