New driver iCpiI2c for real I/O with I2C
Makefile.in  21 add rules to make iCpiI2C and its dependencies.
iCpiFace.c   13 make help text clearer, replacing the word IEC
                with actual examples IXn or QXn.
iCpiI2c.c     1 I/O driver for iCserver in the immediate C environment of a
                Raspberry Pi handling real 16 bit inputs and/or 16 bit outputs
                for each MCP23017 controller attached to a Raspberry Pi via 8
                multiplexed I2C busses of a PCA9548A I2C Switch, or from a number
                of direct GPIO pins on the Raspberry Pi or both.
m             8 add rules to make iCpiI2C and its dependencies.
makeAll       9 add rules to make iCpiI2C and its dependencies.
mcp23017.c    1 communication via I2C multiplexed by a PCA9548A to MCP23017
                16-Bit I/O expanders.
mcp23017.h    1 communication via I2C multiplexed by a PCA9548A to MCP23017
                16-Bit I/O expanders.
misc.c        9 move piFaceCAD code to pifacecad.c
pifacecad.c   2 move piFaceCAD code from misc.c

    Id: src/Makefile.in 1.83
    Id: src/iCpiFace.c 1.16
    Id: src/iCpiI2C.c 1.1
    Id: src/m 1.25
    Id: src/makeAll 1.48
    Id: src/mcp23017.c 1.1
    Id: src/mcp23017.h 1.1
    Id: src/misc.c 1.22
    Id: src/pifacecad.c 1.4 <- pifacecad.h,v

diff --git a/src/makeAll b/src/makeAll
--- a/src/makeAll
+++ b/src/makeAll
@@ -38,9 +38,10 @@ usage ()
     echo '	-L	make libict.a only' >&2
     echo '	-S	make libict.so without YYDEBUG if OSTYPE ~= linux' >&2
     echo '	-G	make goserver if golang is installed' >&2
-    echo '	-P	make iCpiFace digital I/O for RASPBERRYPI, YYDEBUG only' >&2
+    echo '	-P	make iCpiFace real SIO digital I/O for RASPBERRYPI, YYDEBUG only' >&2
     echo '		   + iCgpioPUD for RASPBERRYPI as SUID auxiliary program' >&2
-    echo '	-V	make iCpiPWM analog I/O for RASPBERRYPI, PWM, serVo and ADC' >&2
+    echo '	-X	make iCpiI2C real I2C digital I/O for RASPBERRYPI, YYDEBUG only' >&2
+    echo '	-V	make iCpiPWM real analog I/O for RASPBERRYPI, PWM, serVo and ADC' >&2
     echo '	-R	make icr only without modifying cexe.c' >&2
     echo '	-T	make ict only without modifying cexe.c' >&2
     echo '	-N	make const test internal constant expression compiler only' >&2
@@ -61,7 +62,7 @@ usage ()
     echo '	-z	echo compiler calls with all options for debugging (not -q)' >&2
     echo '	-h	this help text' >&2
     echo '	NOTE: if any option is changed, make clean is automatically executed' >&2
-    echo '	$Id: makeAll 1.47 $' >&2
+    echo '	$Id: makeAll 1.48 $' >&2
 }
 
 makeLib ()
@@ -175,6 +176,23 @@ makePiFace ()
     fi
 }
 
+makePiI2C ()
+{
+    if [[ -n "$raspberrypi" ]]; then
+	mv misc.$O icend.$O tcpc.$O rpi_gpio.$O mcp23s17.$O pifacecad.$O Make_tmp 2> /dev/null
+	if [ -d PiI2CObjs ]; then
+	    mv PiI2CObjs/* .
+	else
+	    mkdir PiI2CObjs
+	fi
+	make OPT="-DTCP -DYYDEBUG$o" CFLAGS="$cflags" LDFLAGS="$ldflags" iCpiI2C
+	mv misc.$O icend.$O tcpc.$O rpi_gpio.$O mcp23s17.$O pifacecad.$O PiI2CObjs
+	mv Make_tmp/* . 2> /dev/null
+    else
+	echo "Error makeAll -P: cannot make iCpiI2C for a '$cpu' cpu - only for an 'armv*' on a Raspberry Pi"
+    fi
+}
+
 makeGpioPUD ()
 {
     if [[ -n "$raspberrypi" ]]; then
@@ -217,6 +235,7 @@ L=0
 S=0
 G=0
 P=0
+X=0
 V=0
 R=0
 T=0
@@ -234,7 +253,7 @@ Y=""
 cpu=""
 raspberrypi=""
 
-while getopts ":qgpclrtmCLSPGVRTNMuedsyzhD:W:o:" opt; do
+while getopts ":qgpclrtmCLSPXGVRTNMuedsyzhD:W:o:" opt; do
     case $opt in
     q )	q="q";;		# echo only - dont kill
     g )	cflags="-g";;	# debugging, no optimisation
@@ -249,6 +268,7 @@ while getopts ":qgpclrtmCLSPGVRTNMuedsyzhD:W:o:" opt; do
     S )	S=1; IM_LIB=0;;
     G )	G=1; IM_LIB=0;;
     P )	P=1;;
+    X )	X=1;;
     V )	V=1;;
     R )	R=1;;
     T )	T=1;;
@@ -288,7 +308,7 @@ fi
 if [ $YN -ne 0 ]; then
     Y=" -DYYDEBUG=$YN"
 fi
-if [ $P -eq 0 ] && [ $V -eq 0 ] && ! perl icg.pl $Y$u$d$e$o$s$y icc.h | cmp -s - icg.h; then
+if [ $P -eq 0 ] && [ $X -eq 0 ] && [ $V -eq 0 ] && ! perl icg.pl $Y$u$d$e$o$s$y icc.h | cmp -s - icg.h; then
     echo "Options changed to '$Y$u$d$e$o$s$y'"
     if [ $R -eq 0 ] && [ $T -eq 0 ]; then
 	echo "   make clean"
@@ -356,6 +376,11 @@ if [ $V = 1 ]; then
     makePiPWM  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
+if [ $X = 1 ]; then
+    echo "make OPT=\"-DTCP -DYYDEBUG$o\" CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\" iCpiI2C"
+    makePiI2C  2>&1 | if [ -n "$q" ]; then egrep -i "(\berror|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+fi
+
 rmdir Make_tmp
 exit 0
 
@@ -384,9 +409,10 @@ makeAll - supports Makefile in immediate-C develeopment
     -L      make libict.a only
     -S      make libict.so without YYDEBUG if OSTYPE ~= linux
     -G      make goserver if golang is installed
-    -P      make iCpiFace digital I/O for RASPBERRYPI, YYDEBUG only
-               + iCgpioPUD for RASPBERRYPI as SUID auxiliary program
-    -V      make iCpiPWM analog I/O for RASPBERRYPI, PWM, serVo and ADC
+    -P      make iCpiFace real SIO digital I/O for RASPBERRYPI, YYDEBUG only
+          + iCgpioPUD for RASPBERRYPI as SUID auxiliary program
+    -X      make iCpiI2C real I2C digital I/O for RASPBERRYPI, YYDEBUG only
+    -V      make iCpiPWM real analog I/O for RASPBERRYPI, PWM, serVo and ADC
     -R      make icr only without modifying cexe.c
     -T      make ict only without modifying cexe.c
     -N      make const test internal constant expression compiler
@@ -431,7 +457,7 @@ is via TCP/IP and iCserver.
 with gram.y and lexc.l. It test compiles C sources and generates debugging
 output and possibly error messages.
 
-'iCpiFace' is a real I/O client supporting one or more  PiFace controllers
+B<iCpiFace> is a real I/O client supporting one or more  PiFace controllers
 as well as an optional PiFaceCAD attached to a Raspberry Pi. Each PiFace
 has an 8 bit input and an 8 bit output. The PiFaceCAD has 8 input buttons
 and a 2x16 character text display, which can be modified over the iC network.
@@ -445,9 +471,16 @@ to 2500 microseconds at 20 ms intervals (50 Hz) or as PWM pulses at
 different frequencies with a duty cycle in the range 0 to 100.
 B<iCpiPWM> also handles analog input from an MCP3008 ADC.
 
-'makeAll' keeps the directories 'LibObjs' 'SharedObjs' 'IcrObjs' 'IctObjs'
-'ConstObjs' 'LmainObjs' 'PiFaceObjs' to save object files which differ for
-different targets.  Thus the following rules for 'make' are satisfied:
+B<iCpiI2C> is an I/O client for iCserver in the immediate C environment
+of a Raspberry Pi handling real 16 bit inputs and/or 16 bit outputs for
+each MCP23017 controller attached to a Raspberry Pi via 8 multiplexed
+I2C busses, or from a number of direct GPIO pins on the Raspberry Pi
+or both.
+
+'makeAll' keeps the directories 'LibObjs' 'SharedObjs' 'IcrObjs'
+'IctObjs' 'ConstObjs' 'LmainObjs' 'PiFaceObjs' 'PiI2CObjs' to save
+object files which differ for different targets.  Thus the following
+rules for 'make' are satisfied:
 
   to make immcc, make with OPT=''
   to make libict.a, remove all objects and make with OPT='-DLOAD -DTCP'
@@ -457,6 +490,7 @@ different targets.  Thus the following rules for 'make' are satisfied:
   to make const,      "     "    " and make with OPT='-DTESTCONS'
   to make lmain,      "     "    " and make with OPT='-DLMAIN -DYYDEBUG'
   to make iCpiFace,   "     "    " and make with OPT='-DRASPBERRYPI -DTCP -DYYDEBUG'
+  to make iCpiI2C,    "     "    " and make with OPT='-DRASPBERRYPI -DTCP -DYYDEBUG'
 
     makeAll       # makes 'immcc' 'libict.a' and 'libict.so'
                   # without YYDEBUG support
