RCS	icc.v	1.91	2002/09/03 17:50:32
make ict and libict.a without YYDEBUG and -d100 trace output, icc with trace output
make icc ict libict.a and lmain with optional -DYYDEBUG (icc and lmain default)
add auxiliary script m to make all iC project files with debugging

CVS-ID: src/AuxTools/AuxTools.v 1.91
CVS-ID: src/AuxTools/Readme_develop 1.2
CVS-ID: src/AuxTools/m 1.1
CVS-ID: src/Makefile.in 1.31
CVS-ID: src/Readme_develop 1.2
CVS-ID: src/iCmake 1.22
CVS-ID: src/icc.c 1.19
CVS-ID: src/icc.h 1.45
CVS-ID: src/icc.v 1.91
CVS-ID: src/ict.c 1.32
CVS-ID: src/link.c 1.18
CVS-ID: src/load.c 1.36
CVS-ID: src/m 1.1
CVS-ID: src/main.c 1.37
CVS-ID: src/makeAll 1.11
CVS-ID: src/manifest 1.6
CVS-ID: src/rsff.c 1.32
CVS-ID: src/scan.c 1.23
CVS-ID: src/tcpc.c 1.12

diff --git a/src/makeAll b/src/makeAll
--- a/src/makeAll
+++ b/src/makeAll
@@ -10,7 +10,7 @@
 #   For more information about this program, or for information on how
 #   to contact the author, see the README file or <john@je-wulff.de>
 #
-#	make icc ict libict.a
+#	make icc ict libict.a lmain
 #
 #	use egrep rather than grep -E so it works on older Unix systems
 #
@@ -18,17 +18,62 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/}' [-qh] [path]' >&2
+    echo 'Usage:	'${0##*/}' [-qh]' >&2
     echo '	call make for icc, ict and libict.a with the correct options' >&2
-    echo '	path is optionally supplied by Makefile for executing scripts' >&2
-    echo '	in the correct path (default ./)' >&2
     echo '	-q	output only headings and error messages' >&2
+    echo '	-c	make icc with YYDEBUG -t trace output possible' >&2
+    echo '	-t	make ict with YYDEBUG -t trace output possible' >&2
+    echo '	-l	make libict.a with YYDEBUG -t trace output possible' >&2
+    echo '	-m	make lmain with YYDEBUG' >&2
+    echo '		see usage of icc, ict and applications for other options' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: makeAll,v 1.10 2002/09/02 12:33:14 jw Exp $' >&2
+    echo '	$Id: makeAll,v 1.11 2002/09/03 17:30:13 jw Exp $' >&2
+}
+
+makeIct ()
+{
+    mv main.o comp.o genr.o gram.o lexc.o link.o rsff.o scan.o Make_tmp
+    if [ -d PptcObjs ]; then
+	mv PptcObjs/* .
+    else
+	mkdir PptcObjs
+    fi
+    make OPT="-DTCP$t" ict
+    mv main.o ict.o comp.o genr.o gram.o lexc.o link.o rsff.o scan.o PptcObjs
+    mv Make_tmp/* .
+}
+
+makeLib ()
+{
+    mv scid.o link.o rsff.o scan.o Make_tmp
+    if [ -d LoadObjs ]; then
+	mv LoadObjs/* .
+    else
+	mkdir LoadObjs
+    fi
+    make OPT="-DLOAD -DTCP$l" libict.a
+    mv ict.o scid.o link.o rsff.o scan.o LoadObjs
+    mv Make_tmp/* .
+}
+
+makeLmain ()
+{
+    mv gram.o lexc.o Make_tmp
+    if [ -d LmainObjs ]; then
+	mv LmainObjs/* .
+    else
+	mkdir LmainObjs
+    fi
+    make OPT="-DLMAIN$m" lmain
+    mv gram.o lexc.o LmainObjs
+    mv Make_tmp/* .
 }
 
 q=""
-path="./"
+c=""
+t=""
+l=""
+m=""
 
 while [ $# -gt 0 ]; do
     case $1 in
@@ -37,6 +82,10 @@ while [ $# -gt 0 ]; do
 	while [ -n "$option" ]; do
 	    case $option in
 	    q*)	q=1;;	# echo only - dont kill
+	    c*)	c="-DYYDEBUG";;
+	    t*)	t=" -DYYDEBUG";;
+	    l*)	l=" -DYYDEBUG";;
+	    m*)	m=" -DYYDEBUG";;
 	    h*)	usage; exit 255;;
 	    *)	x=${option#?}; option=${option%$x}
 	    	echo "$name: unexpected option $option in $1" >&2
@@ -50,18 +99,25 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if [ $# -gt 0 ]; then
-    path=$1
+if [ -f Make_tmp ]; then
+    echo 'Error makeAll: Make_tmp exists as file ??? - nothing made' >&2
+    exit 1;
 fi
+test -d Make_tmp || mkdir Make_tmp;
 
 if test -f cexe.c_empty && ! cmp -s cexe.c cexe.c_empty; then
     rm -f cexe.o
     cp -p cexe.c_empty cexe.c
 fi
-echo "make icc"
-make OPT='-DYYDEBUG' icc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
-echo "make ict"
-${path}makeIct  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
-echo "make libict.a"
-${path}makeLib  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+
+echo "make OPT=$c icc"
+make OPT=$c icc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+echo "make OPT=-DTCP$t ict"
+makeIct  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+echo "make OPT=-DLOAD -DTCP$l libict.a"
+makeLib  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+echo "make OPT=-DLMAIN$m lmain"
+makeLmain  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+
+rmdir Make_tmp
 true
