RCS	makex	1.4	intermediate version
allow use of other pplc versions with -v<N>

CVS-ID: src/makex 1.4

diff --git a/src/makex b/src/makex
--- a/src/makex
+++ b/src/makex
@@ -8,15 +8,17 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/} 'file ...' >&2
+    echo 'Usage:	'${0##*/} [-lh] [-v<N>] 'file ...' >&2
     echo '	-l	link all the iC files into one application' >&2
+    echo '	-v<N>	use pplc<N> eg pplc1 pplc2 ...' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: makex,v 1.3 2000/11/11 13:36:37 jw Exp $' >&2
+    echo '	$Id: makex,v 1.4 2000/11/23 16:48:46 jw Exp $' >&2
 }
 
 link=0
 flag=noerror
 a=""
+v=""
 
 while [[ $# > 0 ]]; do
     case $1 in
@@ -24,8 +26,14 @@ while [[ $# > 0 ]]; do
     -*)	option=${1#?}
 	while [[ -n "$option" ]]; do
 	    case "$option" in
-	    l*)	link=1
-		;;
+	    l*)	link=1;;
+	    v*)	option=${option#?};
+		if [[ -n $option ]]; then
+		    v=$option;
+		else
+		    shift; v=$1;
+		fi
+		break;;
 	    h*)	usage; exit 255;;
 	    *) aflag="-$option"; break;;
 	    esac
@@ -52,14 +60,14 @@ for f in $*; do
     fi
     echo $file
     if [[ $link != 1 ]]; then
-	if pplc -d74 -o $base.c -l $base.lst $file; then
+	if pplc$v -d74 -o $base.c -l $base.lst $file; then
 	    gcc -g -DYYDEBUG -o $base $base.c list.c load.a
 	fi
     else
 	if [[ $first != $base ]]; then
 	    a="-a"
 	fi
-	if pplc $a -d74 -o $base.c -l $base.lst $file; then
+	if pplc$v $a -d74 -o $base.c -l $base.lst $file; then
 	    list="$list $base.c"
 	else
 	    list="$list ERROR:$base.c"
@@ -73,6 +81,6 @@ if [[ $link = 1 ]]; then
 	echo "link $first from$list"
 	gcc -g -DYYDEBUG -o $first $list list.c load.a
     else
-	echo "pplc compile errors in $list" >&2
+	echo "pplc$v compile errors in $list" >&2
     fi
 fi
