RCS	im	1.4	intermediate version
add -O<opt> option and -x option

CVS-ID: src/AuxTools/im 1.4

diff --git a/src/AuxTools/im b/src/AuxTools/im
--- a/src/AuxTools/im
+++ b/src/AuxTools/im
@@ -3,25 +3,31 @@
 usage ()
 {
   echo 'Usage:' >&2
-  echo "  $name[ -e xxx][ -ASzh]" >&2
+  echo "  $name[ -e xxx][ -ASxzh]" >&2
   echo "	-e xxx	execute with iC compiler xxx (default $ic)" >&2
   echo '	-A	compile output ARITHMETIC ALIAS nodes for symbol debugging' >&2
   echo '	-S	strict compile - all immediate variables must be declared' >&2
+  echo '	-O <l>  optimisation -O0 none -O1 bit -O2 arithmetic -O3 both (default)' >&2
+  echo '	-x	auxiliary files .iC_list1.h etc not deleted; no pplstfix' >&2
   echo '	-z	echo compiler calls with all options for debugging' >&2
   echo '	-h	this help text' >&2
-  echo '	$Id: im,v 1.3 2007/03/26 14:40:42 archiv Exp $' >&2
+  echo '	$Id: im,v 1.4 2007/03/28 10:01:31 archiv Exp $' >&2
 }
 
 name=${0##*/}
 ic='./immcc'
 A=""
+O=""
+x=0
 z=0
 
-while getopts ":e:ASzh" opt; do
+while getopts ":e:ASO:xzh" opt; do
     case $opt in
     e )	ic="$OPTARG";;
     A )	A="$A -A";;
     S )	A="$A -S";;
+    O )	A="$A -O$OPTARG";;
+    x )	A="$A -d4000"; x="1";;
     z )	z=1;;
     h )	usage; exit 0;;
     \?)	echo "$name: illegal option '-$OPTARG'"; usage; exit 127;;
@@ -48,3 +54,8 @@ for f in $*; do
 	fi
     fi
 done
+
+# clean up temporary files generated by immcc compiler unless -x option
+if [ $x -ne 1 ]; then
+    rm -f .iC_list1.h .iC_list2.h
+fi
