RCS	icc.v	1.64	2001/04/09 19:23:14
change names to iC... for uniformity and to avoid name clashes
remove word register - extend live processing
clean up connecting and data preparation
send ftype RI_BIT for logical CH_BIT to iClive to get correct display colours
flash pulses shorter than 50 ms on any node

CVS-ID: src/AuxTools/AuxTools.v 1.64
CVS-ID: src/AuxTools/mkpp 1.4
CVS-ID: src/Makefile.in 1.19
CVS-ID: src/README 1.5
CVS-ID: src/comp.h 1.19
CVS-ID: src/comp.y 1.49
CVS-ID: src/genr.c 1.38
CVS-ID: src/iCbox 1.33
CVS-ID: src/iClive 1.14
CVS-ID: src/iCmake 1.17
CVS-ID: src/iCserver 1.23
CVS-ID: src/icc.h 1.29
CVS-ID: src/icc.v 1.64
CVS-ID: src/ict.c 1.25
CVS-ID: src/init.c 1.12
CVS-ID: src/link.c 1.14
CVS-ID: src/load.c 1.24
CVS-ID: src/main.c 1.21
CVS-ID: src/makeIct 1.8
CVS-ID: src/outp.c 1.39
CVS-ID: src/rsff.c 1.24
CVS-ID: src/scan.c 1.15
CVS-ID: src/symb.c 1.7
CVS-ID: src/tcpc.c 1.9

diff --git a/src/AuxTools/mkpp b/src/AuxTools/mkpp
--- a/src/AuxTools/mkpp
+++ b/src/AuxTools/mkpp
@@ -2,7 +2,7 @@
 
 ########################################################################
 #
-#	make icc$v.v of icc$v ict$v and ict$v.a
+#	make icc$v.v of icc$v ict$v and libict$v.a
 #
 ########################################################################
 
@@ -11,7 +11,7 @@ usage ()
     echo 'Usage:	'${0##*/}' [-dh] [ver ...]' >&2
     echo '	-d	diff previously made files' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: mkpp,v 1.3 2001/02/21 16:21:41 jw Exp $' >&2
+    echo '	$Id: mkpp,v 1.4 2001/03/30 15:19:46 jw Exp $' >&2
 }
 
 while [[ $# > 0 ]]; do
@@ -45,13 +45,13 @@ for w in $versions; do
 	    echo "Error: icc$v does not exist" >&2
 	elif [[ ! -f ict$v ]]; then
 	    echo "Error: ict$v does not exist" >&2
-	elif [[ ! -f ict$v.a ]]; then
-	    echo "Error: ict$v.a does not exist" >&2
+	elif [[ ! -f libict$v.a ]]; then
+	    echo "Error: libict$v.a does not exist" >&2
 	else
 	    if [[ -n "$d" ]]; then
-		mkv icc$v ict$v ict$v.a | diff - icc$v.v
+		mkv icc$v ict$v libict$v.a | diff - icc$v.v
 	    else
-		mkv icc$v ict$v ict$v.a > icc$v.v
+		mkv icc$v ict$v libict$v.a > icc$v.v
 	    fi
 	fi
     fi
