RCS	icc.v	1.60	2001/02/21 16:22:22
use the name icc instead of pplc throughout the project

CVS-ID: src/AuxTools/AuxTools.v 1.60
CVS-ID: src/AuxTools/mklst 1.6
CVS-ID: src/AuxTools/mkpp 1.3
CVS-ID: src/AuxTools/mz 1.6
CVS-ID: src/ICServer 1.16
CVS-ID: src/Makefile 1.14
CVS-ID: src/cexe.h 1.10
CVS-ID: src/comp.y 1.45
CVS-ID: src/genr.c 1.35
CVS-ID: src/ibsd.c 1.3
CVS-ID: src/icc.c 1.13
CVS-ID: src/icc.h 1.24
CVS-ID: src/icc.v 1.60
CVS-ID: src/icl.c 1.6
CVS-ID: src/ict.c 1.15
CVS-ID: src/init.c 1.10
CVS-ID: src/link.c 1.11
CVS-ID: src/load.c 1.20
CVS-ID: src/main.c 1.17
CVS-ID: src/makeIct 1.3
CVS-ID: src/makeall 1.4
CVS-ID: src/makeload 1.7
CVS-ID: src/outp.c 1.34
CVS-ID: src/rsff.c 1.18
CVS-ID: src/scan.c 1.11
CVS-ID: src/symb.c 1.5
CVS-ID: src/tcpc.c 1.5
CVS-ID: src/tcpc.h 1.5

diff --git a/src/AuxTools/mkpp b/src/AuxTools/mkpp
--- a/src/AuxTools/mkpp
+++ b/src/AuxTools/mkpp
@@ -2,7 +2,7 @@
 
 ########################################################################
 #
-#	make pplc$v.v of pplc$v pptc$v and load$v.a
+#	make icc$v.v of icc$v ict$v and ict$v.a
 #
 ########################################################################
 
@@ -11,7 +11,7 @@ usage ()
     echo 'Usage:	'${0##*/}' [-dh] [ver ...]' >&2
     echo '	-d	diff previously made files' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: mkpp,v 1.2 2001/02/08 20:23:10 jw Exp $' >&2
+    echo '	$Id: mkpp,v 1.3 2001/02/21 16:21:41 jw Exp $' >&2
 }
 
 while [[ $# > 0 ]]; do
@@ -41,17 +41,17 @@ for w in $versions; do
     if [[ ! -L $w ]]; then
 	v=${w##*[a-z]}
 	echo "### $v ###"
-	if [[ ! -f pplc$v ]]; then
-	    echo "Error: pplc$v does not exist" >&2
-	elif [[ ! -f pptc$v ]]; then
-	    echo "Error: pptc$v does not exist" >&2
-	elif [[ ! -f load$v.a ]]; then
-	    echo "Error: load$v.a does not exist" >&2
+	if [[ ! -f icc$v ]]; then
+	    echo "Error: icc$v does not exist" >&2
+	elif [[ ! -f ict$v ]]; then
+	    echo "Error: ict$v does not exist" >&2
+	elif [[ ! -f ict$v.a ]]; then
+	    echo "Error: ict$v.a does not exist" >&2
 	else
 	    if [[ -n "$d" ]]; then
-		mkv pplc$v pptc$v load$v.a | diff - pplc$v.v
+		mkv icc$v ict$v ict$v.a | diff - icc$v.v
 	    else
-		mkv pplc$v pptc$v load$v.a > pplc$v.v
+		mkv icc$v ict$v ict$v.a > icc$v.v
 	    fi
 	fi
     fi
