RCS	mm	1.16	intermediate version
change to getopts commandline switch selection
add support for -O0 to -O3

CVS-ID: src/AuxTools/mm 1.16

diff --git a/src/AuxTools/mm b/src/AuxTools/mm
--- a/src/AuxTools/mm
+++ b/src/AuxTools/mm
@@ -7,74 +7,53 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/}' [-ASRxzNh] [-v<N>] [-d<opt>]' >&2
-    echo '	-v<N>	use ict<N> eg ict1 ict2 ... with libict1.a libict2.a ...' >&2
-    echo '	-d<opt>	call immcc with extra -d<opt> orred into normal -d474' >&2
-    echo '	-A	compile output ARITHMETIC ALIAS nodes for symbol debugging' >&2
-    echo '	-S	strict compile - all immediate variables must be declared' >&2
-    echo '	-P	pedantic: warning if variable contains $ (default $ allowed)' >&2
-    echo '	-PP	pedantic-error: error if variable contains $' >&2
-    echo '	-R      no maximum error count (default: abort after 100 errors)' >&2
-    echo '	-i	produce file.ini with load info but no INITIALIZATION' >&2
-    echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
-    echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
-    echo '	-x	auxiliary files .iC_list1.h .iC_list2.h not deleted' >&2
-    echo '	-z	echo compiler calls with all options for debugging' >&2
-    echo '	-N	No nice with calls of immcc and gcc compilers (default is nice)' >&2
-    echo '	-h	this help text' >&2
-    echo '	uses iCmake -v<N> -d<opt> to make each line of the list pm.lt' >&2
-    echo '	which has mostly individual lines naming one source eg. xxx.ic' >&2
-    echo '	but may also have lines like "-l a.ic a1.ic a2.ic" for linking' >&2
-    echo 'Author:	John E. Wulff        <john@je-wulff.de>' >&2
-    echo '$Id: mm,v 1.15 2005/09/30 15:52:10 jw Exp $' >&2
+  echo "Usage:	${0##*/} [-ASRxzNh][ -v<N>][ -d<opt>][ -O<level>]" >&2
+  echo '	-v<N>	use ict<N> eg ict1 ict2 ... with libict1.a libict2.a ...' >&2
+  echo '	-d<opt>	call immcc with extra -d<opt> orred into normal -d474' >&2
+  echo '	-A	compile output ARITHMETIC ALIAS nodes for symbol debugging' >&2
+  echo '	-S	strict compile - all immediate variables must be declared' >&2
+  echo '	-P	pedantic: warning if variable contains $ (default $ allowed)' >&2
+  echo '	-PP	pedantic-error: error if variable contains $' >&2
+  echo '	-O <l>  optimisation -O0 none -O1 bit -O2 arithmetic -O3 both (default)' >&2
+  echo '	-R      no maximum error count (default: abort after 100 errors)' >&2
+  echo '	-i	produce file.ini with load info but no INITIALIZATION' >&2
+  echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
+  echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
+  echo '	-x	auxiliary files .iC_list1.h .iC_list2.h not deleted' >&2
+  echo '	-z	echo compiler calls with all options for debugging' >&2
+  echo '	-N	No nice with calls of immcc and gcc compilers (default is nice)' >&2
+  echo '	-h	this help text' >&2
+  echo '	uses iCmake -v<N> -d<opt> -O<level> to make each line of the list pm.lt' >&2
+  echo '	which has mostly individual lines naming one source eg. xxx.ic' >&2
+  echo '	but may also have lines like "-l a.ic a1.ic a2.ic" for linking' >&2
+  echo 'Author:	John E. Wulff        <john@je-wulff.de>' >&2
+  echo '$Id: mm,v 1.16 2007/04/02 18:16:54 jw Exp $' >&2
 }
 
 A=""
 z=0
 I=""
 
-while [[ $# -gt 0 ]]; do
-    case $1 in
-    -)	shift; break;;
-    -*)	option=${1#?}
-	while [[ -n "$option" ]]; do
-	    case "$option" in
-	    v*)	option=${option#?}
-		if [ -n "$option" ]; then
-		    A="$A -v$option"
-		else
-		    echo "-v must specify an option";
-		    usage; exit 254;
-		fi
-		break;;
-	    d*)	option=${option#?}
-		if [ -n "$option" ]; then
-		    A="$A -d$option"
-		else
-		    echo "-d must specify an option";
-		    usage; exit 254;
-		fi
-		break;;
-	    x*)	A="$A -x";;
-	    A*)	A="$A -A";;
-	    S*)	A="$A -S";;
-	    P*)	A="$A -P";;
-	    R*)	A="$A -R";;
-	    N*)	A="$A -N";;
-	    i*) I=" -i";;
-	    I*) I=" -I";;
-	    J*) I=" -J";;
-	    z*)	z=1;A="$A -z";;
-	    h*)	usage; exit 255;;
-	    *)	echo "unknown flag -$option";
-		usage; exit 255;;
-	    esac
-	    option=${option#?}
-	done;;
-    *)	break;;
+while getopts ":d:ASO:PRiIJ6xzh" opt; do
+    case $opt in
+    v )	A="$A -v$OPTARG";;
+    d ) A="$A -d$OPTARG";;
+    A )	A="$A -A";;
+    S )	A="$A -S";;
+    O )	A="$A -O$OPTARG";;
+    P )	A="$A -P";;
+    R )	A="$A -R";;
+    N )	A="$A -N";;
+    i ) I=" -i";;
+    I ) I=" -I";;
+    J ) I=" -J";;
+    x )	A="$A -x";;
+    z )	z=1;A="$A -z";;
+    h )	usage; exit 0;;
+    \?)	echo "$name: illegal option '-$OPTARG'"; usage; exit 127;;
     esac
-    shift
 done
+shift $(($OPTIND - 1))
 
 while true; do
     read line
