RCS	mm	1.23	intermediate version
extend tools - see -h options

CVS-ID: src/AuxTools/mm 1.23

diff --git a/src/AuxTools/mm b/src/AuxTools/mm
--- a/src/AuxTools/mm
+++ b/src/AuxTools/mm
@@ -19,12 +19,16 @@ usage ()
   echo '		duplicate arithmetic expressions -O7 all (default)' >&2
   echo '	-R      no maximum error count (default: abort after 100 errors)' >&2
   echo '	-s	link with static library libict.a (default libict.so)' >&2
+  echo '	-e	link all targets with -lefence to test with Electric Fence' >&2
   echo '	-a      immac: output for loop control and %define lines as comments' >&2
+  echo '		make only iCa files - listed by ml in pma.lt' >&2
+  echo '		listed by ml in pda.lt for generated dependencies to compare' >&2
   echo '	-L      generate auxiliary 'file.log' for debugging immac translation' >&2
   echo '	-N	No nice with calls of immcc and gcc compilers (default: nice)' >&2
   echo '	-j	produce file.ini with load info but no INITIALIZATION' >&2
   echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
   echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
+  echo '	-6	produce logic generation listing file.lst6 and file.cc=(cexe.c)' >&2
   echo '	-x	auxiliary files .iC_list1.h .iC_list2.h not deleted' >&2
   echo '	-z	echo compiler calls with all options for debugging' >&2
   echo '	-h	this help text' >&2
@@ -32,14 +36,17 @@ usage ()
   echo '	which has mostly individual lines naming one source eg. xxx.ic' >&2
   echo '	but may also have lines like "-l a.ic a1.ic a2.ic" for linking' >&2
   echo 'Author:	John E. Wulff        <immediateC@gmail.com>' >&2
-  echo '$Id: mm,v 1.22 2012/04/12 23:55:45 jw Exp $' >&2
+  echo '$Id: mm,v 1.23 2012/06/03 08:00:19 jw Exp $' >&2
 }
 
 A=" -f"
-z=0
+a=""
+x=""
+z=""
 I=""
+g=""
 
-while getopts ":d:gASO:PRsaLNjIJ6xzh" opt; do
+while getopts ":d:gASO:PRseaLNjIJ6xzh" opt; do
     case $opt in
     v )	A="$A -v$OPTARG";;
     d ) A="$A -d$OPTARG";;
@@ -50,28 +57,65 @@ while getopts ":d:gASO:PRsaLNjIJ6xzh" opt; do
     P )	A="$A -P";;
     R )	A="$A -R";;
     s )	A="$A -s";;
-    a )	A="$A -a";;
+    e )	A="$A -e";;
+    a )	a="a";A="$A -a";;
     L )	A="$A -L";;
     N )	A="$A -N";;
     j ) I=" -j";;
     I ) I=" -I";;
     J ) I=" -J";;
-    x )	A="$A -x";;
-    z )	z=1;A="$A -z";;
+    6 ) g="6";;
+    x )	x=" -x";A="$A -x";;
+    z )	z=" -z";A="$A -z";;
     h )	usage; exit 0;;
     \?)	echo "$name: illegal option '-$OPTARG'"; usage; exit 127;;
     esac
 done
 shift $(($OPTIND - 1))
 
-while true; do
-    read line
-    if [[ -z "$line" ]]; then
-	break
+if [ -f pm.lt ]; then
+    if [ -z "$g" ]; then
+	while true; do
+	    read line
+	    if [[ -z "$line" ]]; then
+		break
+	    fi
+	    if [ -n "$z" ]; then
+		echo "iCmake$I$A $line" >&2
+	    fi
+	    iCmake$I$A $line
+	done < pm$a.lt 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\./ s//\/tmp\/x./' > Init.out
+    else
+	rm -f /tmp/cexe.c			# just in case
+	immcc -c < /dev/null			# uses installed iC compiler
+	mv cexe.c /tmp				# empty cexe.c for comparison
+	while true; do
+	    read line
+	    if [[ -z "$line" ]]; then
+		break
+	    fi
+	    f=${line%.*}	# no cexe.c made for $line with -l linked files
+	    f=${f##* }		# remove leading options -P ...
+	    if [ -n "$z" ]; then
+		echo "iCmake$I$A -6t $line" >&2
+	    fi
+	    rm -f cexe.c
+	    iCmake$I$A -6t $line
+	    if test -f cexe.c &&
+		! diff -q -I'was built with' cexe.c /tmp/cexe.c > /dev/null; then
+		if [ -n "$z" ]; then
+		    echo "mv cexe.c $f.cc" >&2
+		fi
+		mv cexe.c $f.cc;
+	    fi
+	done < pm$a.lt 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\./ s//\/tmp\/x./' > Init.out6
+	rm -f /tmp/cexe.c
     fi
-    if [ $z -eq 1 ]; then
-	echo "iCmake$I$A $line" >&2
+    # clean up temporary files generated by immcc compiler unless -x option
+    if [ -n "$x"  ]; then
+	rm -f .iC_list1.h .iC_list2.h ic[0-9].*
     fi
-    iCmake$I$A $line
-done < pm.lt 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\./ s//\/tmp\/x./' > Init.out
-rm -rf ic[0-9].*
+else
+    echo "no list of files 'pp.lt' found - use ml to generate it" >&2
+    usage; exit 255;
+fi
