RCS	AuxTools.v	1.128	2016/02/09 06:56:23
ready for git import

CVS-ID: src/AuxTools/AuxTools.v 1.128
CVS-ID: src/AuxTools/Readme_develop 1.22
CVS-ID: src/AuxTools/filetype.vim 1.4
CVS-ID: src/AuxTools/ic.ssh 1.2
CVS-ID: src/AuxTools/ic.vim 1.10
CVS-ID: src/AuxTools/mm 1.26
CVS-ID: src/AuxTools/my 1.20
CVS-ID: src/AuxTools/tt 1.39
CVS-ID: src/AuxTools/tx 1.7
CVS-ID: src/AuxTools/wulff.vim 1.2

diff --git a/src/AuxTools/mm b/src/AuxTools/mm
--- a/src/AuxTools/mm
+++ b/src/AuxTools/mm
@@ -25,9 +25,10 @@ usage ()
   echo '		listed by ml in pda.lt for generated dependencies to compare' >&2
   echo '	-L      generate auxiliary 'file.log' for debugging immac translation' >&2
   echo '	-N	No nice with calls of immcc and gcc compilers (default: nice)' >&2
-  echo '	-j	produce file.ini with load info but no INITIALIZATION' >&2
-  echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
-  echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
+  echo '	-E	store error output of iC and C compile in file.ini' >&2
+  echo '	-j	append output of an initial run to file.ini      (implies -s)' >&2
+  echo '	-I	append output of run INITIALIZATION only to file.ini  ( " -s)' >&2
+  echo '	-J	append output of full INITIALIZATION info to file.ini ( " -s)' >&2
   echo '	-6	produce logic generation listing file.lst6 and file.cc=(cexe.c)' >&2
   echo '	-x	auxiliary files .iC_list1.h .iC_list2.h not deleted' >&2
   echo '	-z	echo compiler calls with all options for debugging' >&2
@@ -36,17 +37,18 @@ usage ()
   echo '	which has mostly individual lines naming one source eg. xxx.ic' >&2
   echo '	but may also have lines like "-l a.ic a1.ic a2.ic" for linking' >&2
   echo 'Author:	John E. Wulff        <immediateC@gmail.com>' >&2
-  echo '$Id: mm,v 1.25 2015/10/31 05:34:52 jw Exp $' >&2
+  echo '$Id: mm,v 1.26 2015/11/01 04:34:12 jw Exp $' >&2
 }
 
 A=" -f"
 a=""
 x=""
 z=""
+E=""
 I=""
 g=""
 
-while getopts ":d:gASO:PRseaLNjIJ6xzh" opt; do
+while getopts ":d:gASO:PRseaLNEjIJ6xzh" opt; do
     case $opt in
     v )	A="$A -v$OPTARG";;
     d ) A="$A -d$OPTARG";;
@@ -61,6 +63,7 @@ while getopts ":d:gASO:PRseaLNjIJ6xzh" opt; do
     a )	a="a";A="$A -a";;
     L )	A="$A -F";;		# option changed from iCmake -L to -F jw 20151015
     N )	A="$A -N";;
+    E ) E=" -E";;
     j ) I=" -j";;
     I ) I=" -I";;
     J ) I=" -J";;
@@ -81,9 +84,9 @@ if [ -f pm.lt ]; then
 		break
 	    fi
 	    if [ -n "$z" ]; then
-		echo "iCmake$I$A $line" >&2
+		echo "iCmake$I$E$A $line" >&2
 	    fi
-	    iCmake$I$A $line
+	    iCmake$I$E$A $line
 	done < pm$a.lt 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\./ s//\/tmp\/x./' > Init.out
     else
 ##	rm -f /tmp/cexe.c			# just in case
@@ -97,10 +100,10 @@ if [ -f pm.lt ]; then
 	    f=${line%.*}	# no cexe.c made for $line with -l linked files
 	    f=${f##* }		# remove leading options -P ...
 	    if [ -n "$z" ]; then
-		echo "iCmake$I$A -6t $line" >&2
+		echo "iCmake$I$E$A -6t $line" >&2
 	    fi
 	    rm -f cexe.c
-	    iCmake$I$A -6t $line
+	    iCmake$I$E$A -6t $line
 	    if test -f cexe.c &&
 		! diff -q -I'was built with' cexe.c /tmp/cexe.c > /dev/null; then
 		if [ -n "$z" ]; then
@@ -116,6 +119,6 @@ if [ -f pm.lt ]; then
 	rm -f .iC_list1.h .iC_list2.h ic[0-9].*
     fi
 else
-    echo "no list of files 'pp.lt' found - use ml to generate it" >&2
+    echo "no list of files 'pm.lt' found - use ml to generate it" >&2
     usage; exit 255;
 fi
diff --git a/src/AuxTools/my b/src/AuxTools/my
--- a/src/AuxTools/my
+++ b/src/AuxTools/my
@@ -15,26 +15,28 @@ usage ()
   echo '	-s	link with static library libict.a (default libict.so)' >&2
   echo '	-e	link all targets with -lefence to test with Electric Fence' >&2
   echo '	-N	No nice with calls of immcc and gcc compilers (default: nice)' >&2
-  echo '	-j	produce file.ini with load info but no INITIALIZATION' >&2
-  echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
-  echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
+  echo '	-E	store error output of iC and C compile in file.ini' >&2
+  echo '	-j	append output of an initial run to file.ini      (implies -s)' >&2
+  echo '	-I	append output of run INITIALIZATION only to file.ini  ( " -s)' >&2
+  echo '	-J	append output of full INITIALIZATION info to file.ini ( " -s)' >&2
   echo '	-6	produce logic generation listing file.lst6 and file.cc=(cexe.c)' >&2
   echo '	-x	auxiliary files .iC_list1.h .iC_list2.h not deleted' >&2
   echo '	-z	echo compiler calls with all options for debugging' >&2
   echo '	-h	this help text' >&2
   echo 'uses immcc -d76 -d<opt> -O<level> x.ic to make each line of the list pp.lt' >&2
   echo 'uses immcc -d74 -d<opt> -O<level> -o x.c x.ic to make each line of the list pp.lt' >&2
-  echo '	$Id: my,v 1.19 2015/02/27 21:31:32 jw Exp $' >&2
+  echo '	$Id: my,v 1.20 2015/11/01 04:34:32 jw Exp $' >&2
 }
 
 d=""
 x=""
 z=""
 A=" -f"
+E=""
 I=""
 g=""
 
-while getopts ":d:gASO:PRseNjIJ6xzh" opt; do
+while getopts ":d:gASO:PRseNEjIJ6xzh" opt; do
     case $opt in
     d ) d="$d -d$OPTARG";;
     g )	A="$A -g";;
@@ -46,6 +48,7 @@ while getopts ":d:gASO:PRseNjIJ6xzh" opt; do
     s )	A="$A -s";;
     e )	A="$A -e";;
     N )	A="$A -N";;
+    E ) E=" -E";;
     j ) I=" -j";;
     I ) I=" -I";;
     J ) I=" -J";;
@@ -63,9 +66,9 @@ if [ -f pp.lt ]; then
 	for file in $(cat pp.lt); do
 	    f=${file%.*}
 	    if [ -n "$z" ]; then
-		echo "iCmake$I$d$A $f.ic" >&2
+		echo "iCmake$I$E$d$A $f.ic" >&2
 	    fi
-	    iCmake$I$d$A $f.ic
+	    iCmake$I$E$d$A $f.ic
 	done 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\./ s//\/tmp\/x./' > Init.out
     else
 ##	rm -f /tmp/cexe.c			# just in case
@@ -74,10 +77,10 @@ if [ -f pp.lt ]; then
 	for file in $(cat pp.lt); do
 	    f=${file%.*}
 	    if [ -n "$z" ]; then
-		echo "iCmake$I$d$A -6t $f.ic" >&2
+		echo "iCmake$I$E$d$A -6t $f.ic" >&2
 	    fi
 	    rm -f cexe.c
-	    iCmake$I$d$A -6t $f.ic
+	    iCmake$I$E$d$A -6t $f.ic
 	    if test -f cexe.c &&
 		! diff -q -I'was built with' cexe.c /tmp/cexe.c > /dev/null; then
 		if [ -n "$z" ]; then
diff --git a/src/AuxTools/tt b/src/AuxTools/tt
--- a/src/AuxTools/tt
+++ b/src/AuxTools/tt
@@ -9,7 +9,7 @@
 version()
 {
   echo 'Author:	John E. Wulff        <immediateC@gmail.com>' >&2
-  echo '$Id: tt,v 1.38 2015/02/27 21:31:32 jw Exp $' >&2
+  echo '$Id: tt,v 1.39 2015/11/01 04:33:48 jw Exp $' >&2
 }
 
 usage()
@@ -41,9 +41,10 @@ usage()
   echo '		and make only iCa files and compare them with "<dir1>a"' >&2
   echo '	-L      generate auxiliary 'file.log' for debugging immac translation' >&2
   echo '	-N	No nice with calls of immcc and gcc compilers (default: nice)' >&2
-  echo '	-j	produce file.ini with load info but no INITIALIZATION' >&2
-  echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
-  echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
+  echo '	-E	store error output of iC and C compile in file.ini' >&2
+  echo '	-j	append output of an initial run to file.ini      (implies -s)' >&2
+  echo '	-I	append output of run INITIALIZATION only to file.ini  ( " -s)' >&2
+  echo '	-J	append output of full INITIALIZATION info to file.ini ( " -s)' >&2
   echo '	-6	produce logic generation listing file.lst6 and file.cc=(cexe.c)' >&2
   echo '	-t <string of directory names for Test1 group> default Test1 Test9 Test11 Test12 Test13' >&2
   echo '	-T <string of directory names for Test2 group> default Test2 - Test8, Test10' >&2
@@ -99,6 +100,7 @@ e=""
 ao="x"
 A=""
 L=""
+E=""
 I=""
 g=""
 pd="pd"
@@ -110,7 +112,7 @@ test2=""
 Test1='Test1 Test9 Test11 Test12 Test13'
 Test2='Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test10'
 
-while getopts ":cm:d:lwrgASO:PRseaLNjIJ6x:f:F:t:T:zvh" opt; do
+while getopts ":cm:d:lwrgASO:PRseaLNEjIJ6x:f:F:t:T:zvh" opt; do
     case $opt in
     c )	c="c";;
     m )	m="$OPTARG";;
@@ -129,6 +131,7 @@ while getopts ":cm:d:lwrgASO:PRseaLNjIJ6x:f:F:t:T:zvh" opt; do
     a )	ao=a;;
     L )	L=" -L";;
     N )	A="$A -N";;
+    E ) E=" -E";;
     j ) I=" -j";;
     I ) I=" -I";;
     J ) I=" -J";;
@@ -173,7 +176,7 @@ shift $(($OPTIND - 1))
 
 l="$l$x$f$F"
 if [ -n "$z" ]; then
-    echo "c = !$c! A = !$A! I = !$I! m = !$m! v = !$v! d = !$d! l = !$l! g = !$g! pd = !$pd!"
+    echo "c = !$c! A = !$A! I = !$I! E = !$E! m = !$m! v = !$v! d = !$d! l = !$l! g = !$g! pd = !$pd!"
 fi
 
 d1=$1
@@ -227,8 +230,8 @@ if [ -n "$test1" ]; then
 		    fi
 		    ml
 		    rm -f $(cat p[g$g].lt)
-		    echo; echo "========== $t mm$I$v$A$L$ae"
-		    mm$I$v$A$L$ae	# do twice if -a
+		    echo; echo "========== $t mm$I$E$v$A$L$ae"
+		    mm$I$E$v$A$L$ae	# do twice if -a
 		    ml
 		fi
 		if [ -n "$d1" ]; then
@@ -288,8 +291,8 @@ if [ -n "$test2" ]; then
 	    if [ -z "$c" ]; then
 		ml
 		rm -f $(cat p[g$g].lt)
-		echo; echo "========== $t my$I$v$A"
-		my$I$v$A
+		echo; echo "========== $t my$I$E$v$A"
+		my$I$E$v$A
 		ml
 	    fi
 	    if [ -n "$d1" ]; then
