RCS	mm	1.10	intermediate version
add -R option

CVS-ID: src/AuxTools/mm 1.10

diff --git a/src/AuxTools/mm b/src/AuxTools/mm
--- a/src/AuxTools/mm
+++ b/src/AuxTools/mm
@@ -7,11 +7,12 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/}' [-h] [-v<N>] [-y<opt>]' >&2
+    echo 'Usage:	'${0##*/}' [-ASRxzNh] [-v<N>] [-y<opt>]' >&2
     echo '	-v<N>	use ict<N> eg ict1 ict2 ... with libict1.a libict2.a ...' >&2
     echo '	-y<opt>	call icc with extra -d<opt> orred into normal -d474' >&2
     echo '	-A	compile output ARITHMETIC ALIAS nodes for symbol debugging' >&2
     echo '	-S	strict compile - all immediate variables must be declared' >&2
+    echo '	-R      no maximum error count (default: abort after 100 errors)' >&2
     echo '	-x	auxiliary files .iC_list1.h .iC_list2.h not deleted' >&2
     echo '	-z	echo compiler calls with all options for debugging' >&2
     echo '	-N	No nice with calls of icc and gcc compilers (default is nice)' >&2
@@ -20,7 +21,7 @@ usage ()
     echo '	which has mostly individual lines naming one source eg. xxx.ic' >&2
     echo '	but may also have lines like "-l a.ic a1.ic a2.ic" for linking' >&2
     echo 'Author:	John E. Wulff        <john@je-wulff.de>' >&2
-    echo '$Id: mm,v 1.9 2005/03/16 18:26:53 jw Exp $' >&2
+    echo '$Id: mm,v 1.10 2005/04/21 17:42:05 jw Exp $' >&2
 }
 
 v=""
@@ -51,6 +52,7 @@ while [[ $# > 0 ]]; do
 	    x*)	v="$v -x";;
 	    A*)	v="$v -A";;
 	    S*)	v="$v -S";;
+	    R*)	v="$v -R";;
 	    N*)	v="$v -N";;
 	    z*)	z=1;v="$v -z";;
 	    h*)	usage; exit 255;;
