RCS	icc.v	1.98	2003/12/31 21:04:15
add -DINT_MAX=32767 for systems with 16 bit int
and -DLONG16 to handle long arithmetic on 16 bit systems (slower)
add handling for long I/O with ILn and QLn Gates
IGNORE forked child processes - no more defunct processs

CVS-ID: src/AuxTools/AuxTools.v 1.98
CVS-ID: src/AuxTools/mo 1.13
CVS-ID: src/cexe.h 1.18
CVS-ID: src/comp.h 1.39
CVS-ID: src/comp.y 1.80
CVS-ID: src/genr.c 1.55
CVS-ID: src/gram.y 1.16
CVS-ID: src/iCbox 1.37
CVS-ID: src/iClive 1.30
CVS-ID: src/iCserver 1.29
CVS-ID: src/icc.c 1.23
CVS-ID: src/icc.h 1.48
CVS-ID: src/icc.v 1.98
CVS-ID: src/icg.h 1.3
CVS-ID: src/ict.c 1.35
CVS-ID: src/lexc.l 1.20
CVS-ID: src/load.c 1.38
CVS-ID: src/main.c 1.39
CVS-ID: src/makeAll 1.14
CVS-ID: src/outp.c 1.69
CVS-ID: src/rsff.c 1.34
CVS-ID: src/scan.c 1.25
CVS-ID: src/tcpc.h 1.10

diff --git a/src/AuxTools/mo b/src/AuxTools/mo
--- a/src/AuxTools/mo
+++ b/src/AuxTools/mo
@@ -8,21 +8,30 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/}' [-h] [iCtarget ...]' >&2
+    echo 'Usage:	'${0##*/}' [-CTszh] [iCtarget ...]' >&2
+    echo 'Makes a dedicated icc or ict compiler with integrated arithmetic functions' >&2
+    echo 'from iCtarget for the run-time environment. ' >&2
     echo '      -C	uses icc -c to make a dedicated icc for each iCtarget' >&2
     echo '		output the listings produced to directory ListC' >&2
     echo '      -T	uses ict -c to make a dedicated ict for each iCtarget' >&2
     echo '		output the listings produced to directory ListT' >&2
     echo '		(default option)' >&2
+    echo '	-s	make with -DINT_MAX=32767 (makeAll with this option first)' >&2
+    echo '		(on a 16 bit system INT_MAX is 32767 and -s is not required)' >&2
+    echo '		simulates compilation for a 16 bit system, which does' >&2
+    echo '		no 32 bit arithmetic and rejects QL.. and IL.. I/O unless' >&2
+    echo '	-z	make with -DLONG16        (makeAll with this option first)' >&2
+    echo '		produces code for long int arithmetic on a 16 bit system' >&2
     echo 'if no iCtargets are specified, each single entry of file pm.lt is made' >&2
     echo '   outputs the common output to ListC/Init.out or ListT/Init.out' >&2
     echo '   restores a plain icc or ict at the end of the test run' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: mo,v 1.12 2003/12/29 21:27:45 jw Exp $' >&2
+    echo '	$Id: mo,v 1.13 2003/12/30 17:23:51 jw Exp $' >&2
 }
 
 ic='ict'
 op='T'
+p='T'
 
 while [ $# > 0 ]; do
     case $1 in
@@ -30,8 +39,10 @@ while [ $# > 0 ]; do
     -*)	option=${1#?}
 	while [ -n "$option" ]; do
 	    case "$option" in
-	    C*)	ic='icc';op='C';;
-	    T*)	ic='ict';op='T';;
+	    C*)	ic='icc';op='C';p='C';;
+	    T*)	ic='ict';op='T';p='T';;
+	    s*)	op="${op}s";;
+	    z*)	op="${op}z";;
 	    h*)	usage; exit 255;;
 	    *)	echo "unknown flag -$option";
 		usage; exit 255;;
@@ -43,7 +54,7 @@ while [ $# > 0 ]; do
     shift
 done
 
-test -d List$op || mkdir List$op;
+test -d List$p || mkdir List$p;
 
 if [ $# != 0 ]; then
     for f in $*; do
@@ -54,14 +65,14 @@ if [ $# != 0 ]; then
 	fi
 	if [ -f "$file" ]; then
 	    echo "$file";
-	    $ic -c -d474 -l List$op/$base.lst $file
-	    cp -f cexe.c List$op/$base.c
+	    $ic -c -d474 -l List$p/$base.lst $file
+	    cp -f cexe.c List$p/$base.c
 	    cd ..
 	    rm -f cexe.o $ic	# new cexe.o too soon for make sometimes
 	    makeAll -$op 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
 	    cd - > /dev/null
 	    if [[ -f ../$ic ]]; then	# use locally generated compiler
-		../$ic -d500 $file > List$op/$base.ini
+		../$ic -d500 $file > List$p/$base.ini
 	    else
 		echo make $ic failed
 	    fi
@@ -76,19 +87,19 @@ else
 	fi
 	if [ -f "$file" ]; then
 	    echo "$file";
-	    $ic -c -d474 -l List$op/$base.lst $file
-	    cp -f cexe.c List$op/$base.c
+	    $ic -c -d474 -l List$p/$base.lst $file
+	    cp -f cexe.c List$p/$base.c
 	    cd ..
 	    rm -f cexe.o $ic	# new cexe.c too soon for make sometimes
 	    makeAll -$op 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
 	    cd - > /dev/null
 	    if [[ -f ../$ic ]]; then	# use locally generated compiler
-		../$ic -d500 $file > List$op/$base.ini
+		../$ic -d500 $file > List$p/$base.ini
 	    else
 		echo make $ic failed
 	    fi
 	fi
-    done > List$op/Init.out 2>&1;
+    done > List$p/Init.out 2>&1;
     $ic -c < /dev/null			# restore plain icc or ict
     cd ..
     rm -f cexe.o $ic	# new cexe.c too soon for make sometimes
diff --git a/src/makeAll b/src/makeAll
--- a/src/makeAll
+++ b/src/makeAll
@@ -21,7 +21,7 @@
 
 usage ()
 {
-    echo 'Usage:	'${0##*/}' [-qh]' >&2
+    echo 'Usage:	'${0##*/}' [-qgctlmCTLMszh]' >&2
     echo '	call make for icc, ict and libict.a with the correct options' >&2
     echo '	-q	output only headings and error messages' >&2
     echo '	-g	compile for debugging and no optimisation (default -O2)' >&2
@@ -34,8 +34,14 @@ usage ()
     echo '	-T	make ict only without modifying cexe.c' >&2
     echo '	-L	make libict.a only' >&2
     echo '	-M	make lmain only' >&2
+    echo '	-s	make with -DINT_MAX=32767 (make clean required first)' >&2
+    echo '		(on a 16 bit system INT_MAX is 32767 and -s is not required)' >&2
+    echo '		simulates compilation for a 16 bit system, which does' >&2
+    echo '		no 32 bit arithmetic and rejects QL.. and IL.. I/O unless' >&2
+    echo '	-z	make with -DLONG16        (make clean required first)' >&2
+    echo '		produces code for long int arithmetic on a 16 bit system' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: makeAll,v 1.13 2003/10/12 20:57:47 jw Exp $' >&2
+    echo '	$Id: makeAll,v 1.14 2003/12/30 17:13:04 jw Exp $' >&2
 }
 
 makeIct ()
@@ -46,7 +52,7 @@ makeIct ()
     else
 	mkdir PptcObjs
     fi
-    make OPT="-DTCP$t" CFLAGS="$cflags" ict
+    make OPT="-DTCP$t$s$z" CFLAGS="$cflags" ict
     mv main.o ict.o comp.o genr.o gram.o lexc.o link.o rsff.o scan.o PptcObjs
     mv Make_tmp/* .
 }
@@ -59,7 +65,7 @@ makeLib ()
     else
 	mkdir LoadObjs
     fi
-    make OPT="-DLOAD -DTCP$l" CFLAGS="$cflags" libict.a
+    make OPT="-DLOAD -DTCP$l$s$z" CFLAGS="$cflags" libict.a
     mv ict.o scid.o link.o rsff.o scan.o LoadObjs
     mv Make_tmp/* .
 }
@@ -72,7 +78,7 @@ makeLmain ()
     else
 	mkdir LmainObjs
     fi
-    make OPT="-DLMAIN$m" CFLAGS="$cflags" lmain
+    make OPT="-DLMAIN$m$s$z" CFLAGS="$cflags" lmain
     mv gram.o lexc.o LmainObjs
     mv Make_tmp/* .
 }
@@ -82,6 +88,8 @@ c=""
 t=""
 l=""
 m=""
+s=""
+z=""
 C=0
 T=0
 L=0
@@ -101,6 +109,8 @@ while [ $# -gt 0 ]; do
 	    t*)	t=" -DYYDEBUG";;
 	    l*)	l=" -DYYDEBUG";;
 	    m*)	m=" -DYYDEBUG";;
+	    s*)	s=" -DINT_MAX=32767";;
+	    z*)	z=" -DLONG16";;
 	    C*)	C=1; ALL=0;;
 	    T*)	T=1; ALL=0;;
 	    L*)	L=1; ALL=0;;
@@ -132,22 +142,22 @@ if [ $ALL = 1 ]; then
 fi
 
 if [ $ALL = 1 ] || [ $C = 1 ]; then
-    echo "make OPT=$c CFLAGS=$cflags icc"
-    make OPT=$c CFLAGS="$cflags" icc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
+    echo "make OPT=\"$c$s$z\" CFLAGS=\"$cflags\" icc"
+    make OPT="$c$s$z" CFLAGS="$cflags" icc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $ALL = 1 ] || [ $T = 1 ]; then
-    echo "make OPT=-DTCP$t CFLAGS=$cflags ict"
+    echo "make OPT=\"-DTCP$t$s$z\" CFLAGS=\"$cflags\" ict"
     makeIct  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $ALL = 1 ] || [ $L = 1 ]; then
-    echo "make OPT=-DLOAD -DTCP$l CFLAGS=$cflags libict.a"
+    echo "make OPT=\"-DLOAD -DTCP$l$s$z\" CFLAGS=\"$cflags\" libict.a"
     makeLib  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
 if [ $ALL = 1 ] || [ $M = 1 ]; then
-    echo "make OPT=-DLMAIN$m CFLAGS=$cflags lmain"
+    echo "make OPT=\"-DLMAIN$m$s$z\" CFLAGS=\"$cflags\" lmain"
     makeLmain  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|unrecognized|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
 fi
 
