RCS	mo	1.16	intermediate version
fix making of /tmp/cexe.c - must be deleted so another user can use this script

CVS-ID: src/AuxTools/mo 1.16

diff --git a/src/AuxTools/mo b/src/AuxTools/mo
--- a/src/AuxTools/mo
+++ b/src/AuxTools/mo
@@ -31,7 +31,7 @@ usage ()
     echo '   restores a plain icr or ict at the end of the test run' >&2
     echo '	-m	make each entry from pm.lt instead of default pa.lt (takes longer)' >&2
     echo '	-h	this help text' >&2
-    echo '	$Id: mo,v 1.15 2004/01/03 11:03:19 jw Exp $' >&2
+    echo '	$Id: mo,v 1.16 2004/01/14 10:48:22 jw Exp $' >&2
 }
 
 ic='ict'
@@ -80,11 +80,9 @@ if [ ! -x $devp/$ic ]; then
     exit 254
 fi
 
-cd $devp
-    $ic -c < /dev/null			# uses installed iC compiler
-    rm -f /tmp/cexe.c			# with local cexe.h
-    cp cexe.c /tmp			# empty cexe.c
-cd - > /dev/null
+rm -f /tmp/cexe.c			# just in case
+$ic -c < /dev/null			# uses installed iC compiler
+mv cexe.c /tmp				# empty cexe.c for comparison
 
 if [ $# != 0 ]; then
     test -d List$p || mkdir List$p;
@@ -141,8 +139,8 @@ elif [ -f $list ]; then
 	fi
     done > List$p/List$p.out 2>&1;
     if [ -f /tmp/cexe.c ]; then
-	cp /tmp/cexe.c .
 	cd $devp			# restore plain icr or ict
+	cp /tmp/cexe.c .
 	rm -f cexe.o $ic		# new cexe.c too soon for make sometimes
 	makeAll -$op 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
 	cd - > /dev/null
@@ -150,3 +148,4 @@ elif [ -f $list ]; then
 else
     echo "ERROR: no list of test iC sources '$list' found - no $ic made" >&2
 fi
+rm -f /tmp/cexe.c			# clean up in case another user wants to use it
