RCS	my	1.8	intermediate version
change iC compiler from icc to immcc (Intel C compiler is also icc)

CVS-ID: src/AuxTools/my 1.8

diff --git a/src/AuxTools/my b/src/AuxTools/my
--- a/src/AuxTools/my
+++ b/src/AuxTools/my
@@ -3,7 +3,7 @@
 usage ()
 {
     echo 'Usage:	'${0##*/}' [-ASRiIJ6xzh] [-y<opt>]' >&2
-    echo '	-y<opt>	call icc with extra -d<opt> orred into normal -d474' >&2
+    echo '	-y<opt>	call immcc with extra -d<opt> orred into normal -d474' >&2
     echo '	-A	compile output ARITHMETIC ALIAS nodes for symbol debugging' >&2
     echo '	-S	strict compile - all immediate variables must be declared' >&2
     echo '	-R      no maximum error count (default: abort after 100 errors)' >&2
@@ -14,9 +14,9 @@ usage ()
     echo '	-x	auxiliary files .iC_list1.h .iC_list2.h not deleted' >&2
     echo '	-z	echo compiler calls with all options for debugging' >&2
     echo '	-h	this help text' >&2
-    echo 'uses icc -d76 -y<opt> x.ic to make each line of the list pp.lt' >&2
-    echo 'uses icc -d74 -y<opt> -o x.c x.ic to make each line of the list pp.lt' >&2
-    echo '	$Id: my,v 1.7 2005/05/19 09:09:53 jw Exp $' >&2
+    echo 'uses immcc -d76 -y<opt> x.ic to make each line of the list pp.lt' >&2
+    echo 'uses immcc -d74 -y<opt> -o x.c x.ic to make each line of the list pp.lt' >&2
+    echo '	$Id: my,v 1.8 2005/07/04 13:44:18 jw Exp $' >&2
 }
 
 v=""
@@ -67,9 +67,9 @@ if [ -f pp.lt ]; then
 	    echo $file
 	    f=${file%.*}
 	    if [ "$z" = 1 ]; then
-		echo "icc -d76$v$A -l $f.lst6 $f.ic" >&2
+		echo "immcc -d76$v$A -l $f.lst6 $f.ic" >&2
 	    fi
-	    icc -d76$v$A -l $f.lst6 $f.ic;
+	    immcc -d76$v$A -l $f.lst6 $f.ic;
 	done 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\.o\((\.[a-z][a-z]*+0x[0-9a-f]*)\)*:/ s//\/tmp\/x.o:/' > Init.out6
     fi
     for file in $(cat pp.lt); do
@@ -80,7 +80,7 @@ if [ -f pp.lt ]; then
 	fi
 	iCmake$I$y$A $f.ic
     done 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\.o\((\.[a-z][a-z]*+0x[0-9a-f]*)\)*:/ s//\/tmp\/x.o:/' > Init.out
-    # clean up temporary files generated by icc compiler unless -x option
+    # clean up temporary files generated by immcc compiler unless -x option
     if [ "$x" != 1 ]; then
 	rm -f .iC_list1.h .iC_list2.h ic[0-9].*
     fi
