RCS	AuxTools.v	1.100	2004/05/19 16:03:49
update tools ml mm mo and my

CVS-ID: src/AuxTools/AuxTools.v 1.100
CVS-ID: src/AuxTools/ml 1.8
CVS-ID: src/AuxTools/mm 1.7
CVS-ID: src/AuxTools/mo 1.17
CVS-ID: src/AuxTools/my 1.3

diff --git a/src/AuxTools/my b/src/AuxTools/my
--- a/src/AuxTools/my
+++ b/src/AuxTools/my
@@ -4,14 +4,16 @@ usage ()
 {
     echo 'Usage:	'${0##*/}' [-h] [-y<opt>]' >&2
     echo '	-y<opt>	call icc with extra -d<opt> orred into normal -d474' >&2
+    echo '	-x	auxiliary files _list1.h _list2.h _list_.c not deleted' >&2
     echo '	-z	echo compiler calls with all options for debugging' >&2
     echo '	-h	this help text' >&2
     echo 'uses icc -d76 -y<opt> x.ic to make each line of the list pp.lt' >&2
     echo 'uses icc -d74 -y<opt> -o x.c x.ic to make each line of the list pp.lt' >&2
-    echo '	$Id: my,v 1.2 2004/02/08 11:22:24 jw Exp $' >&2
+    echo '	$Id: my,v 1.3 2004/02/20 15:11:46 jw Exp $' >&2
 }
 
 v=""
+x=0
 z=0
 
 while [[ $# > 0 ]]; do
@@ -28,6 +30,7 @@ while [[ $# > 0 ]]; do
 		    usage; exit 254;
 		fi
 		break;;
+	    x*)	x=1;v="$v -d4000";;
 	    z*)	z=1;;
 	    h*)	usage; exit 255;;
 	    *)	echo "unknown flag -$option";
@@ -39,20 +42,28 @@ while [[ $# > 0 ]]; do
     esac
     shift
 done
-# $Id: my,v 1.2 2004/02/08 11:22:24 jw Exp $
-for file in $(cat pp.lt); do
-    echo $file
-    f=${file%.*}
-    if [ "$z" = 1 ]; then
-	echo "icc -d76$v -l $f.lst6 $f.ic" >&2
+if [ -f pp.lt ]; then
+    for file in $(cat pp.lt); do
+	echo $file
+	f=${file%.*}
+	if [ "$z" = 1 ]; then
+	    echo "icc -d76$v -l $f.lst6 $f.ic" >&2
+	fi
+	icc -d76$v -l $f.lst6 $f.ic;
+    done > Init.out6 2>&1
+    for file in $(cat pp.lt); do
+	echo $file
+	f=${file%.*}
+	if [ "$z" = 1 ]; then
+	    echo "icc -d74$v -A -l $f.lst -o $f.c $f.ic" >&2
+	fi
+	icc -d74$v -A -l $f.lst -o $f.c $f.ic;
+    done > Init.out 2>&1
+    # clean up temporary files generated by icc compiler unless -x option
+    if [ "$x" != 1 ]; then
+	rm -f _list1.h _list2.h _list_.c ic[0-9].*
     fi
-    icc -d76$v -l $f.lst6 $f.ic;
-done > Init.out6 2>&1
-for file in $(cat pp.lt); do
-    echo $file
-    f=${file%.*}
-    if [ "$z" = 1 ]; then
-	echo "icc -d74$v -A -l $f.lst -o $f.c $f.ic" >&2
-    fi
-    icc -d74$v -A -l $f.lst -o $f.c $f.ic;
-done > Init.out 2>&1
+else
+    echo "no list of files 'pp.lt' found - use ml to generate it" >&2
+    usage; exit 255;
+fi
