RCS	AuxTools.v	1.111	2007/03/26 12:50:00
modify tt, add tx

CVS-ID: src/AuxTools/AuxTools.v 1.111
CVS-ID: src/AuxTools/Readme_develop 1.12
CVS-ID: src/AuxTools/m 1.7
CVS-ID: src/AuxTools/saveX 1.2
CVS-ID: src/AuxTools/tt 1.23
CVS-ID: src/AuxTools/tx 1.3
CVS-ID: src/AuxTools/update 1.4

diff --git a/src/AuxTools/saveX b/src/AuxTools/saveX
--- a/src/AuxTools/saveX
+++ b/src/AuxTools/saveX
@@ -5,7 +5,7 @@
 #
 ########################################################################
 
-# $Id: saveX,v 1.1 2007/02/24 10:55:26 jw Exp $
+# $Id: saveX,v 1.2 2007/03/22 18:01:54 jw Exp $
 
 name=${0##*/}
 vp='X'		## save directory prefix
@@ -37,13 +37,22 @@ if [ -f pd.lt ]; then
 	    previous="$vp$n"
 	    let n=$n+1
 	    head="$vp$n"
-	    if ! Mdiff -kLeq $(cat p[d6].lt) $previous; then
+	    if ! Mdiff -kLeq -I'ic[0-6c]\.' -IAborted $(cat p[d6].lt) $previous; then
 		echo "#### $name $head"
 		mkdir $head
 		cd $head
-		ln -s ../$previous/* .
+		for f in ../$previous/*; do
+		    if [ -L $f ]; then
+			cp -a $f .
+		    elif [ -f $f ]; then
+			ln -s $f .
+		    else
+			echo "**** Error: $name has strange file $f - not backed up"
+		    fi
+		done
+		rm -f $(Mdiff -Lle * ..)	# remove links to files which no longer exist
 		cd ..
-		cp --remove-destination -p $(Mdiff -kLel $(cat p[d6].lt) $head) $head
+		cp --remove-destination -p $(Mdiff -kLel -I'ic[0-6c]\.' -IAborted $(cat p[d6].lt) $head) $head
 	    else
 		echo "**** Error: $name directory will get no new files - no $head made"
 	    fi
@@ -64,13 +73,22 @@ if [ -f pd.lt ]; then
 	    let m=$m+1
 	fi
 	branch="$w$m"
-	if ! Mdiff -kLeq $(cat p[d6].lt) $previous; then
+	if ! Mdiff -kLeq -I'ic[0-6c]\.' -IAborted $(cat p[d6].lt) $previous; then
 	    echo "#### $name $branch"
 	    mkdir $branch
 	    cd $branch
-	    ln -s ../$head/* .
+	    for f in ../$head/*; do
+		if [ -L $f ]; then
+		    cp -a $f .
+		elif [ -f $f ]; then
+		    ln -s $f .
+		else
+		    echo "**** Error: $name has strange file $f - not backed up"
+		fi
+	    done
+	    rm -f $(Mdiff -Lle * ..)	# remove links to files which no longer exist
 	    cd ..
-	    cp --remove-destination -p $(Mdiff -kLel $(cat p[d6].lt) $branch) $branch
+	    cp --remove-destination -p $(Mdiff -kLel -I'ic[0-6c]\.' -IAborted $(cat p[d6].lt) $branch) $branch
 	else
 	    echo "**** Error: $name directory will get no new files - no $branch made"
 	fi
diff --git a/src/AuxTools/update b/src/AuxTools/update
--- a/src/AuxTools/update
+++ b/src/AuxTools/update
@@ -1,5 +1,5 @@
 #! /bin/bash
-# $Id: update,v 1.3 2007/02/23 11:31:02 jw Exp $
+# $Id: update,v 1.4 2007/03/02 09:00:45 jw Exp $
 
 name=${0##*/}
 vp='V'		## save directory prefix
@@ -7,22 +7,28 @@ vn='100'	## save directory start numeral
 wp='W'		## branch directory prefix
 wn='1'		## branch directory start numeral
 vpath="$vp*"
+n=''
 
 if locked -q; then
     for d in $vpath; do
 	if [ -d $d ]; then
-	    cd $d
-	    if locked -vq; then
-		echo "#### $d"
-		echo "==== " $(locked -v)
-		co $(locked -v)
+	    nt=${d#$vp*}
+	    if [[ $nt =~ '[0-9][0-9]*' ]]; then
+		n=$nt
+		cd $d
+		if locked -vq; then
+		    echo "#### $d"
+		    echo "==== " $(locked -v)
+		    co $(locked -v)
+		fi
+		cd ..
+	    else
+		echo "**** Warning: $name '$d' must be '$vp' followed by digits, not '$nt' - ignored"
 	    fi
-	    cd ..
 	fi
     done
-
     if [ $name = 'save' ]; then
-	if [ $d = "$vpath" ]; then
+	if [ -z $n ]; then
 	    head="$vp$vn"
 	    echo "#### $name $head"
 	    mkdir $head
@@ -31,7 +37,6 @@ if locked -q; then
 	    cd ..
 	    cp -p $(locked) $head
 	else
-	    n=${d#$vp*}
 	    previous="$vp$n"
 	    let n=$n+1
 	    head="$vp$n"
@@ -39,43 +44,70 @@ if locked -q; then
 		echo "#### $name $head"
 		mkdir $head
 		cd $head
-		ln -s ../$previous/* .
-		rm -f RCS
-		ln -s ../RCS .
+		for f in ../$previous/*; do
+		    if [ -L $f ]; then
+			cp -a $f .
+		    elif [ -f $f ]; then
+			ln -s $f .
+		    else
+			echo "**** Error: $name has strange file $f - not backed up"
+		    fi
+		done
+		rm -f $(Mdiff -Lle * ..)	# remove links to files which longer exist
 		cd ..
 		cp --remove-destination -p $(Mdiff -kLel $(locked) $head) $head
 	    else
-		echo "**** Error: $name directory will get no new files - no $head made"
+		echo "**** Warning: $name directory will get no new files - no $head made"
 	    fi
 	fi
     elif [ $name = 'branch' ]; then
-	n=${d#$vp*}
-	head="$vp$n"
-	w="$wp${n}_"
-	wpath="$w*"
-	for db in $wpath; do
-	    :	# additional files co in head directory are linked below
-	done
-	if [ $db = "$wpath" ]; then
-	    previous=$head	# wpath is empty
-	    m="$wn"		# usually 1 - can be 0
+	if [ -n $n ]; then
+	    head="$vp$n"
+	    w="$wp${n}_"
+	    wpath="$w*"
+	    db=''
+	    for d in $wpath; do
+		if [ -d $d ]; then
+		    db=$d
+		    cd $db
+		    if locked -vq; then
+			echo "#### $db"
+			echo "==== " $(locked -v)
+			co $(locked -v)
+		    fi
+		    cd ..
+		fi
+	    done
+	    if [ -z $db ]; then
+		previous=$head	# wpath is empty
+		m="$wn"		# usually 1 - can be 0
+	    else
+		m=${db#$w*}
+		previous="$w$m"
+		let m=$m+1
+	    fi
+	    branch="$w$m"
+	    if ! Mdiff -kLeq $(locked) $previous; then
+		echo "#### $name $branch"
+		mkdir $branch
+		cd $branch
+		for f in ../$previous/*; do
+		    if [ -L $f ]; then
+			cp -a $f .
+		    elif [ -f $f ]; then
+			ln -s $f .
+		    else
+			echo "**** Error: $name has strange file $f - not backed up"
+		    fi
+		done
+		rm -f $(Mdiff -Lle * ..)	# remove links to files which longer exist
+		cd ..
+		cp --remove-destination -p $(Mdiff -kLel $(locked) $branch) $branch
+	    else
+		echo "**** Warning: $name directory will get no new files - no $branch made"
+	    fi
 	else
-	    m=${db#$w*}
-	    previous="$w$m"
-	    let m=$m+1
-	fi
-	branch="$w$m"
-	if ! Mdiff -kLeq $(locked) $previous; then
-	    echo "#### $name $branch"
-	    mkdir $branch
-	    cd $branch
-	    ln -s ../$previous/* .
-	    rm -f RCS
-	    ln -s ../RCS .
-	    cd ..
-	    cp --remove-destination -p $(Mdiff -kLel $(locked) $branch) $branch
-	else
-	    echo "**** Error: $name directory will get no new files - no $branch made"
+	    echo "**** Error: $name no 'save' has ever been done - no branch made"
 	fi
     fi
 else
