RCS	tt	1.28	intermediate version
all changes leading to icc.v 1.22 - iCmake -f

CVS-ID: src/AuxTools/tt 1.28

diff --git a/src/AuxTools/tt b/src/AuxTools/tt
--- a/src/AuxTools/tt
+++ b/src/AuxTools/tt
@@ -9,7 +9,7 @@
 version()
 {
   echo 'Author:	John E. Wulff        <john@je-wulff.de>' >&2
-  echo '$Id: tt,v 1.27 2007/12/05 20:23:10 jw Exp $' >&2
+  echo '$Id: tt,v 1.28 2008/08/08 21:07:45 jw Exp $' >&2
 }
 
 usage()
@@ -32,7 +32,7 @@ usage()
   echo '	-O <level> optimisation -O0 none -O1 bit -O2 arithmetic -O4 eliminate' >&2
   echo '		duplicate arithmetic expressions -O7 all (default)' >&2
   echo '	-R      no maximum error count (default: abort after 100 errors)' >&2
-  echo '	-i	produce file.ini with load info but no INITIALIZATION' >&2
+  echo '	-j	produce file.ini with load info but no INITIALIZATION' >&2
   echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
   echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
   echo '	-6	produce logic generation listing file.lst6 in Test2 etc' >&2
@@ -103,7 +103,7 @@ while getopts ":cm:d:lrgASO:PRiIJ6x:f:F:zvh" opt; do
     O )	A="$A -O$OPTARG";;
     P )	if [ -z "$P" ]; then P=" -P";T="pedantic";x="$x -IC.OUTPUT -I__GNUC__ -I__extension__ -I#endif"; fi;A="$A$P";;	# allows -PP => -P -P
     R )	A="$A -R";;
-    i ) I=" -i";;
+    j ) I=" -j";;
     I ) I=" -I";;
     J ) I=" -J";;
     6 ) g="6"; G=" -6"; x="$x -Iic[045]\."; d="_6";;
@@ -154,7 +154,7 @@ if [ -z "$d" -a -z "$c" -a -n "$d1" -a -z "$d2" ]; then
     make $T
 fi
 
-for t in Test1 Test9; do
+for t in Test1 Test9 Test11; do
     if [ -d "$t" -a -z "$g" ]; then
 	cd $t
 	if [ -z "$d2" ]; then
@@ -169,8 +169,8 @@ for t in Test1 Test9; do
 		    if [ -n "$r" ]; then
 			Rdiff p*.lt
 		    fi
-		    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' \$(cat pd.lt) $d1$d"
-		    Mdiff -k$l -I'ic[0-6c]\.' $(cat pd.lt) $d1$d
+		    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' \$(cat pd.lt) $d1$d"
+		    Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $(cat pd.lt) $d1$d
 		else
 		    mkdir $d1$d
 		    if [ -d "$head" ]; then
@@ -187,8 +187,8 @@ for t in Test1 Test9; do
 			done
 			rm -f $(Mdiff -Lle * ..)	# remove links to files which no longer exist
 			cd ..
-			echo "========== $t cp --remove-destination -p \$(Mdiff -kLel -I'ic[0-6c]\.' -IAborted \$(cat pd.lt) $d1$d) $d1$d"
-			cp --remove-destination -p $(Mdiff -kLel -I'ic[0-6c]\.' -IAborted $(cat pd.lt) $d1$d) $d1$d 2> /dev/null
+			echo "========== $t cp --remove-destination -p \$(Mdiff -kLel -I'ic[0-6c]\.' -I'undefined.reference' -IAborted \$(cat pd.lt) $d1$d) $d1$d"
+			cp --remove-destination -p $(Mdiff -kLel -I'ic[0-6c]\.' -I'undefined.reference' -IAborted $(cat pd.lt) $d1$d) $d1$d 2> /dev/null
 		    else
 			echo; echo "========== $t cp -p \$(cat pd.lt) $d1$d"
 			cp -p $(cat pd.lt) $d1$d
@@ -198,8 +198,8 @@ for t in Test1 Test9; do
 	elif [ -d "$d1$d" -a -d "$d2$d" ]; then
 	    cd $d1$d
 	    eval d4="$d3"
-	    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' $d1$d/* $d4$d"
-	    Mdiff -k$l -I'ic[0-6c]\.' $(cat ../pd.lt) $d4$d
+	    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $d1$d/* $d4$d"
+	    Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $(cat ../pd.lt) $d4$d
 	    cd ..
 	else
 	    echo "ERROR: if two <directories> are specified they must exist" >&2
@@ -224,8 +224,8 @@ for t in Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test10; do
 		    if [ -n "$r" ]; then
 			Rdiff p*.lt
 		    fi
-		    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' \$(cat p[d$g].lt) $d1$d"
-		    Mdiff -k$l -I'ic[0-6c]\.' $(cat p[d$g].lt) $d1$d
+		    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' \$(cat p[d$g].lt) $d1$d"
+		    Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $(cat p[d$g].lt) $d1$d
 		else
 		    mkdir $d1$d
 		    if [ -d "$head" ]; then
@@ -242,8 +242,8 @@ for t in Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test10; do
 			done
 			rm -f $(Mdiff -Lle * ..)	# remove links to files which no longer exist
 			cd ..
-			echo "========== $t cp --remove-destination -p \$(Mdiff -kLel -I'ic[0-6c]\.' -IAborted \$(cat pd.lt) $d1$d) $d1$d"
-			cp --remove-destination -p $(Mdiff -kLel -I'ic[0-6c]\.' -IAborted $(cat pd.lt) $d1$d) $d1$d 2> /dev/null
+			echo "========== $t cp --remove-destination -p \$(Mdiff -kLel -I'ic[0-6c]\.' -I'undefined.reference' -IAborted \$(cat pd.lt) $d1$d) $d1$d"
+			cp --remove-destination -p $(Mdiff -kLel -I'ic[0-6c]\.' -I'undefined.reference' -IAborted $(cat pd.lt) $d1$d) $d1$d 2> /dev/null
 		    else
 			echo; echo "========== $t cp -p \$(cat pd.lt) $d1$d"
 			cp -p $(cat pd.lt) $d1$d
@@ -253,8 +253,8 @@ for t in Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test10; do
 	elif [ -d "$d1$d" -a -d "$d2$d" ]; then
 	    cd $d1$d
 	    eval d4="$d3"
-	    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' $d1$d/* $d4$d"
-	    Mdiff -k$l -I'ic[0-6c]\.' $(cat ../p[d$g].lt) $d4$d
+	    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $d1$d/* $d4$d"
+	    Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $(cat ../p[d$g].lt) $d4$d
 	    cd ..
 	else
 	    echo "ERROR: if two <directories> are specified they must exist" >&2
