RCS	tt	1.4	intermediate version
extend functionality with -l option and 2nd directory

CVS-ID: src/AuxTools/tt 1.4

diff --git a/src/AuxTools/tt b/src/AuxTools/tt
--- a/src/AuxTools/tt
+++ b/src/AuxTools/tt
@@ -8,17 +8,22 @@
 
 usage()
 {
-  echo "Usage: $name <directory>" >&2
+  echo "Usage: $name <directory>[ <directory>]" >&2
   echo '	-y<opt>	call icc with extra -d<opt> orred into normal -d474' >&2
+  echo '	-l	list files which differ (default is full diff output)' >&2
   echo '	-x	auxiliary files _list1.h _list2.h _list_.c not deleted' >&2
   echo '	-z	echo compiler calls with all options for debugging' >&2
   echo '	-h	this help text' >&2
   echo '	-	all further arguments are treated as files' >&2
-  echo "	<directory> and <directory>_20000 in" >&2
-  echo "	directory Test1, Test2, Test3 etc" >&2
-  echo "	should contain comparison data." >&2
+  echo "	<directory> or <directory>_<opt> is a sub-directory of" >&2
+  echo "	directory Test1, Test2, Test3 .. Test9 (however many exist)" >&2
+  echo "	<directory> will be created if it does not exit and generated" >&2
+  echo "	files copied to it; if <directory> exists, the generated files" >&2
+  echo "	will be compared with files in <directory> with Mdiff -k" >&2
+  echo "	If a 2nd <directory> is specified the files in all 1st <directory>" >&2
+  echo "	will be compared with files in the 2nd <directory> with Mdiff -k" >&2
   echo 'Author:	J.E. Wulff (john@je-wulff.de)' >&2
-  echo '$Id: tt,v 1.3 2005/01/18 23:05:42 jw Exp $' >&2
+  echo '$Id: tt,v 1.4 2005/01/20 15:14:54 jw Exp $' >&2
 }
 
 ########################################################################
@@ -32,6 +37,7 @@ name=${name%.*}
 
 v=""
 y=""
+l=""
 
 while [ $# -gt 0 ]; do
     case $1 in
@@ -44,10 +50,11 @@ while [ $# -gt 0 ]; do
 		    v="$v -y$option"
 		    y="_$option"
 		else
-		    echo "-y must specify an option";
+		    echo "-y must specify an option in $1" >&2
 		    usage; exit 254;
 		fi
 		break;;
+	    l*)	l="l";;
 	    x*)	v="$v -x";;
 	    z*)	v="$v -z";;
 	    h*)	usage; exit 255;;
@@ -64,22 +71,37 @@ while [ $# -gt 0 ]; do
 done
 
 if [ -n "$1" ]; then
-    date
-    if [ -z "$y" ]; then
-	echo "##### Test0 make test"
+    d1=$1
+    d2=$2
+
+    echo; date
+    if [ -z "$y" -a -z "$d2" ]; then
+	echo; echo "========== Test0 make test"; echo
 	time make test
     fi
 
     t=Test1
     if [ -d "$t" ]; then
 	cd $t
-	echo "##### $t mm$v"
-	time mm$v > Init.out 2>&1
-	if [ -d "$1$y" ]; then
-	    time Mdiff -kl $(cat pd.lt) $1$y
+	if [ -z "$d2" ]; then
+	    echo; echo "========== $t mm$v"
+	    time mm$v > Init.out 2>&1
+	    if [ -d "$d1$y" ]; then
+		echo; echo "========== $t Mdiff -k$l * $d1$y"
+		time Mdiff -k$l $(cat pd.lt) $d1$y
+	    else
+		mkdir $d1$y
+		echo; echo "========== $t cp * $d1$y"
+		cp $(cat pd.lt) $d1$y
+	    fi
+	elif [ -d "$d1$y" -a -d "$d2$y" ]; then
+	    cd $d1$y
+	    echo; echo "========== $t Mdiff -k$l $d1$y/* $d2$y"
+	    time Mdiff -k$l $(cat ../pd.lt) ../$d2$y
+	    cd ..
 	else
-	    mkdir $1$y
-	    cp $(cat pd.lt) $1$y
+	    echo "ERROR: if two <directories> are specified they must exist" >&2
+	    usage
 	fi
 	cd ..
     fi
@@ -87,18 +109,30 @@ if [ -n "$1" ]; then
     for t in Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test9; do
 	if [ -d "$t" ]; then
 	    cd $t
-	    echo "##### $t my$v"
-	    time my$v
-	    if [ -d "$1$y" ]; then
-		time Mdiff -kl $(cat p[d6].lt) $1$y
+	    if [ -z "$d2" ]; then
+		echo; echo "========== $t my$v"
+		time my$v
+		if [ -d "$d1$y" ]; then
+		    echo; echo "========== $t Mdiff -k$l * $d1$y"
+		    time Mdiff -k$l $(cat p[d6].lt) $d1$y
+		else
+		    mkdir $d1$y
+		    echo; echo "========== $t cp * $d1$y"
+		    cp $(cat p[d6].lt) $d1$y
+		fi
+	    elif [ -d "$d1$y" -a -d "$d2$y" ]; then
+		cd $d1$y
+		echo; echo "========== $t Mdiff -k$l $d1$y/* $d2$y"
+		time Mdiff -k$l $(cat ../p[d6].lt) ../$d2$y
+		cd ..
 	    else
-		mkdir $1$y
-		cp $(cat p[d6].lt) $1$y
+		echo "ERROR: if two <directories> are specified they must exist" >&2
+		usage
 	    fi
 	    cd ..
 	fi
     done
-    echo "##### end"
+    echo; echo "========== end"
 else
     usage
     exit 255
