RCS	tt	1.29	intermediate version
add -a option which uses immac -a for mm jobs only

CVS-ID: src/AuxTools/tt 1.29

diff --git a/src/AuxTools/tt b/src/AuxTools/tt
--- a/src/AuxTools/tt
+++ b/src/AuxTools/tt
@@ -9,7 +9,7 @@
 version()
 {
   echo 'Author:	John E. Wulff        <john@je-wulff.de>' >&2
-  echo '$Id: tt,v 1.28 2008/08/08 21:07:45 jw Exp $' >&2
+  echo '$Id: tt,v 1.29 2009/09/07 13:23:44 jw Exp $' >&2
 }
 
 usage()
@@ -32,6 +32,7 @@ usage()
   echo '	-O <level> optimisation -O0 none -O1 bit -O2 arithmetic -O4 eliminate' >&2
   echo '		duplicate arithmetic expressions -O7 all (default)' >&2
   echo '	-R      no maximum error count (default: abort after 100 errors)' >&2
+  echo '	-a      immac: output for loop control and %define lines as comments (mm)' >&2
   echo '	-j	produce file.ini with load info but no INITIALIZATION' >&2
   echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
   echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
@@ -83,6 +84,7 @@ f=""
 F=""
 P=""
 c=""
+a=""
 A=""
 I=""
 g=""
@@ -90,7 +92,7 @@ G=""
 T="test"
 head=""
 
-while getopts ":cm:d:lrgASO:PRiIJ6x:f:F:zvh" opt; do
+while getopts ":cm:d:lrgASO:PRaiIJ6x:f:F:zvh" opt; do
     case $opt in
     c )	c="c";;
     m )	m="$OPTARG";;
@@ -103,6 +105,7 @@ while getopts ":cm:d:lrgASO:PRiIJ6x:f:F:zvh" opt; do
     O )	A="$A -O$OPTARG";;
     P )	if [ -z "$P" ]; then P=" -P";T="pedantic";x="$x -IC.OUTPUT -I__GNUC__ -I__extension__ -I#endif"; fi;A="$A$P";;	# allows -PP => -P -P
     R )	A="$A -R";;
+    a )	A="$A -a"; a=1;;
     j ) I=" -j";;
     I ) I=" -I";;
     J ) I=" -J";;
@@ -149,7 +152,7 @@ if [ -n "$m" ]; then
     echo "== -m\"$m\" =="
 fi
 
-if [ -z "$d" -a -z "$c" -a -n "$d1" -a -z "$d2" ]; then
+if [ -z "$d" -a -z "$c" -a -n "$d1" -a -z "$d2" -a -z "$a" ]; then
     echo; echo "========== Test0 make $T"; echo
     make $T
 fi
@@ -209,60 +212,62 @@ for t in Test1 Test9 Test11; do
     fi
 done
 
-for t in Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test10; do
-    if [ -d "$t" ]; then
-	cd $t
-	if [ -z "$d2" ]; then
-	    if [ -z "$c" ]; then
-		rm -f $(cat p[g$g].lt)
-		echo; echo "========== $t my$I$v$A$G"
-		my$I$v$A$G
-		ml
-	    fi
-	    if [ -n "$d1" ]; then
-		if [ -d "$d1$d" ]; then
-		    if [ -n "$r" ]; then
-			Rdiff p*.lt
-		    fi
-		    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' \$(cat p[d$g].lt) $d1$d"
-		    Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $(cat p[d$g].lt) $d1$d
-		else
-		    mkdir $d1$d
-		    if [ -d "$head" ]; then
-			echo; echo "========== $t link all files from $d1$d to $head or beyond"
-			cd $d1$d
-			for file in ../$head/*; do
-			    if [ -L $file ]; then
-				cp -a $file .
-			    elif [ -f $file ]; then
-				ln -s $file .
-			    else
-				echo "**** Error: $name has strange file $file - not backed up" >&2
-			    fi
-			done
-			rm -f $(Mdiff -Lle * ..)	# remove links to files which no longer exist
-			cd ..
-			echo "========== $t cp --remove-destination -p \$(Mdiff -kLel -I'ic[0-6c]\.' -I'undefined.reference' -IAborted \$(cat pd.lt) $d1$d) $d1$d"
-			cp --remove-destination -p $(Mdiff -kLel -I'ic[0-6c]\.' -I'undefined.reference' -IAborted $(cat pd.lt) $d1$d) $d1$d 2> /dev/null
+if [ -z "$a" ]; then
+    for t in Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test10; do
+	if [ -d "$t" ]; then
+	    cd $t
+	    if [ -z "$d2" ]; then
+		if [ -z "$c" ]; then
+		    rm -f $(cat p[g$g].lt)
+		    echo; echo "========== $t my$I$v$A$G"
+		    my$I$v$A$G
+		    ml
+		fi
+		if [ -n "$d1" ]; then
+		    if [ -d "$d1$d" ]; then
+			if [ -n "$r" ]; then
+			    Rdiff p*.lt
+			fi
+			echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' \$(cat p[d$g].lt) $d1$d"
+			Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $(cat p[d$g].lt) $d1$d
 		    else
-			echo; echo "========== $t cp -p \$(cat pd.lt) $d1$d"
-			cp -p $(cat pd.lt) $d1$d
+			mkdir $d1$d
+			if [ -d "$head" ]; then
+			    echo; echo "========== $t link all files from $d1$d to $head or beyond"
+			    cd $d1$d
+			    for file in ../$head/*; do
+				if [ -L $file ]; then
+				    cp -a $file .
+				elif [ -f $file ]; then
+				    ln -s $file .
+				else
+				    echo "**** Error: $name has strange file $file - not backed up" >&2
+				fi
+			    done
+			    rm -f $(Mdiff -Lle * ..)	# remove links to files which no longer exist
+			    cd ..
+			    echo "========== $t cp --remove-destination -p \$(Mdiff -kLel -I'ic[0-6c]\.' -I'undefined.reference' -IAborted \$(cat pd.lt) $d1$d) $d1$d"
+			    cp --remove-destination -p $(Mdiff -kLel -I'ic[0-6c]\.' -I'undefined.reference' -IAborted $(cat pd.lt) $d1$d) $d1$d 2> /dev/null
+			else
+			    echo; echo "========== $t cp -p \$(cat pd.lt) $d1$d"
+			    cp -p $(cat pd.lt) $d1$d
+			fi
 		    fi
 		fi
+	    elif [ -d "$d1$d" -a -d "$d2$d" ]; then
+		cd $d1$d
+		eval d4="$d3"
+		echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $d1$d/* $d4$d"
+		Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $(cat ../p[d$g].lt) $d4$d
+		cd ..
+	    else
+		echo "ERROR: if two <directories> are specified they must exist" >&2
+		usage
 	    fi
-	elif [ -d "$d1$d" -a -d "$d2$d" ]; then
-	    cd $d1$d
-	    eval d4="$d3"
-	    echo; echo "========== $t Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $d1$d/* $d4$d"
-	    Mdiff -k$l -I'ic[0-6c]\.' -I'undefined.reference' $(cat ../p[d$g].lt) $d4$d
 	    cd ..
-	else
-	    echo "ERROR: if two <directories> are specified they must exist" >&2
-	    usage
 	fi
-	cd ..
-    fi
-done
+    done
+fi
 echo; echo "========== end"
 
 ########################################################################
